module OpenAI
  module Internal
    module Transport
      class BaseClient
        extend OpenAI::Internal::Util::SorbetRuntimeSupport

        type request_components =
          {
            method: Symbol,
            path: String | ::Array[String],
            query: ::Hash[String, (::Array[String] | String)?]?,
            headers: ::Hash[String, (String
            | Integer
            | ::Array[(String | Integer)?])?]?,
            body: top?,
            unwrap: (Symbol
            | Integer
            | ::Array[(Symbol | Integer)]
            | (^(top arg0) -> top))?,
            page: Class?,
            stream: Class?,
            model: OpenAI::Internal::Type::Converter::input?,
            security: { :bearer_auth? => bool, :admin_api_key_auth? => bool }?,
            options: OpenAI::request_opts?
          }
        type request_input =
          {
            method: Symbol,
            url: URI::Generic,
            headers: ::Hash[String, String],
            body: top,
            max_retries: Integer,
            timeout: Float?,
            :follow_redirects? => bool,
            :provider_auth? => Symbol
          }

        MAX_REDIRECTS: 20

        PLATFORM_HEADERS: ::Hash[String, String]

        def self.validate!: (
          OpenAI::Internal::Transport::BaseClient::request_components req
        ) -> void

        def self.should_retry?: (
          Integer status,
          headers: ::Hash[String, String]
        ) -> bool

        def self.request_body_replayable?: (top body) -> bool

        def self.follow_redirect: (
          OpenAI::Internal::Transport::BaseClient::request_input request,
          status: Integer,
          response_headers: ::Hash[String, String]
        ) -> OpenAI::Internal::Transport::BaseClient::request_input

        def self.reap_connection!: (
          Integer | OpenAI::Errors::APIConnectionError status,
          stream: Enumerable[String]?
        ) -> void

        attr_reader base_url: URI::Generic

        attr_reader timeout: Float?

        attr_reader max_retries: Integer

        attr_reader initial_retry_delay: Float

        attr_reader max_retry_delay: Float

        attr_reader headers: ::Hash[String, String]

        attr_reader idempotency_header: String?

        attr_reader logger: OpenAI::_Logger?

        attr_reader log_level: Symbol

        attr_reader on_retry: (^(OpenAI::RetryEvent) -> void)?

        # @api private
        attr_reader requester: OpenAI::_HTTPClient

        def initialize: (
          base_url: String,
          ?timeout: Float?,
          ?max_retries: Integer,
          ?initial_retry_delay: Float,
          ?max_retry_delay: Float,
          ?headers: ::Hash[String, (String
          | Integer
          | ::Array[(String | Integer)?])?],
          ?idempotency_header: String?,
          ?http_client: OpenAI::_HTTPClient?,
          ?logger: OpenAI::_Logger?,
          ?log_level: (Symbol | String)?,
          ?on_retry: (^(OpenAI::RetryEvent) -> void)?
        ) -> void

        private def auth_headers: -> ::Hash[String, String]

        private def prepare_request: (
          OpenAI::Internal::Transport::BaseClient::request_input request,
          redirect_count: Integer,
          retry_count: Integer
        ) -> OpenAI::Internal::Transport::BaseClient::request_input

        private def user_agent: -> String

        private def generate_idempotency_key: -> String

        private def build_request: (
          OpenAI::Internal::Transport::BaseClient::request_components req,
          OpenAI::request_options opts
        ) -> OpenAI::Internal::Transport::BaseClient::request_input

        private def request_replayable?: (
          OpenAI::Internal::Transport::BaseClient::request_input request
        ) -> bool

        private def retry_delay: (
          ::Hash[String, String] headers,
          retry_count: Integer
        ) -> Float

        private def raise_status_error!: (
          url: URI::Generic,
          status: Integer,
          headers: ::Hash[String, String],
          response: top,
          stream: Enumerable[String]
        ) -> bot

        def send_request: (
          OpenAI::Internal::Transport::BaseClient::request_input request,
          redirect_count: Integer,
          retry_count: Integer,
          send_retry_header: bool
        ) {
          -> OpenAI::Internal::Logging::Context
        } -> OpenAI::HTTPClient::Response

        def request: (
          Symbol method,
          String | ::Array[String] path,
          ?query: ::Hash[String, (::Array[String] | String)?]?,
          ?headers: ::Hash[String, (String
          | Integer
          | ::Array[(String | Integer)?])?]?,
          ?body: top?,
          ?unwrap: (Symbol
          | Integer
          | ::Array[(Symbol | Integer)]
          | (^(top arg0) -> top))?,
          ?page: Class?,
          ?stream: Class?,
          ?model: OpenAI::Internal::Type::Converter::input?,
          ?security: { :bearer_auth? => bool, :admin_api_key_auth? => bool }?,
          ?options: OpenAI::request_opts?
        ) -> top

        private def perform_request: (
          OpenAI::Internal::Transport::BaseClient::request_components req
        ) -> [URI::Generic, OpenAI::HTTPClient::Response, OpenAI::Internal::Logging::Context]

        private def finish_request: (
          OpenAI::Internal::Logging::Context log_context,
          OpenAI::HTTPClient::Response response
        ) {
          -> top
        } -> top

        private def parse_response: (
          OpenAI::Internal::Transport::BaseClient::request_components req,
          url: URI::Generic,
          response: OpenAI::HTTPClient::Response
        ) -> top

        def inspect: -> String
      end
    end
  end
end
