module OpenAI
  module Resources
    class Realtime
      class Translations
        class Calls
          def create: (
            sdp: String,
            ?request_options: OpenAI::request_opts?
          ) -> OpenAI::Realtime::CallCreateResponse

          def initialize: (client: OpenAI::Client) -> void
        end
      end
    end
  end
end
