module OpenAI
  module Models
    type completion_choice =
      {
        finish_reason: OpenAI::Models::CompletionChoice::finish_reason,
        index: Integer,
        logprobs: OpenAI::CompletionChoice::Logprobs?,
        text: String
      }

    class CompletionChoice < OpenAI::Internal::Type::BaseModel
      attr_accessor finish_reason: OpenAI::Models::CompletionChoice::finish_reason

      attr_accessor index: Integer

      attr_accessor logprobs: OpenAI::CompletionChoice::Logprobs?

      attr_accessor text: String

      def initialize: (
        finish_reason: OpenAI::Models::CompletionChoice::finish_reason,
        index: Integer,
        logprobs: OpenAI::CompletionChoice::Logprobs?,
        text: String
      ) -> void

      def to_hash: -> {
        finish_reason: OpenAI::Models::CompletionChoice::finish_reason,
        index: Integer,
        logprobs: OpenAI::CompletionChoice::Logprobs?,
        text: String
      }

      type finish_reason = :stop | :length | :content_filter

      module FinishReason
        extend OpenAI::Internal::Type::Enum

        STOP: :stop
        LENGTH: :length
        CONTENT_FILTER: :content_filter

        def self?.values: -> ::Array[OpenAI::Models::CompletionChoice::finish_reason]
      end

      type logprobs =
        {
          text_offset: ::Array[Integer],
          token_logprobs: ::Array[Float],
          tokens: ::Array[String],
          top_logprobs: ::Array[::Hash[Symbol, Float]]
        }

      class Logprobs < OpenAI::Internal::Type::BaseModel
        attr_reader text_offset: ::Array[Integer]?

        def text_offset=: (::Array[Integer]) -> ::Array[Integer]

        attr_reader token_logprobs: ::Array[Float]?

        def token_logprobs=: (::Array[Float]) -> ::Array[Float]

        attr_reader tokens: ::Array[String]?

        def tokens=: (::Array[String]) -> ::Array[String]

        attr_reader top_logprobs: ::Array[::Hash[Symbol, Float]]?

        def top_logprobs=: (
          ::Array[::Hash[Symbol, Float]]
        ) -> ::Array[::Hash[Symbol, Float]]

        def initialize: (
          ?text_offset: ::Array[Integer],
          ?token_logprobs: ::Array[Float],
          ?tokens: ::Array[String],
          ?top_logprobs: ::Array[::Hash[Symbol, Float]]
        ) -> void

        def to_hash: -> {
          text_offset: ::Array[Integer],
          token_logprobs: ::Array[Float],
          tokens: ::Array[String],
          top_logprobs: ::Array[::Hash[Symbol, Float]]
        }
      end
    end
  end
end
