module OpenAI
  module Resources
    class Realtime
      attr_reader client_secrets: OpenAI::Resources::Realtime::ClientSecrets

      attr_reader calls: OpenAI::Resources::Realtime::Calls

      def initialize: (client: OpenAI::Client) -> void
    end
  end
end
