module OpenAI
  module Resources
    class Realtime
      class Translations
        class ClientSecrets
          def create: (
            session: OpenAI::Realtime::RealtimeTranslationSessionCreateRequest
            | ::Hash[Symbol | String, untyped],
            ?expires_after: (OpenAI::Realtime::RealtimeTranslationClientSecretCreateRequest::ExpiresAfter
            | ::Hash[(Symbol | String), untyped])?,
            ?request_options: OpenAI::request_opts?
          ) -> OpenAI::Realtime::RealtimeTranslationClientSecretCreateResponse

          def initialize: (client: OpenAI::Client) -> void
        end
      end
    end
  end
end
