# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseFunctionToolCall < OpenAI::Internal::Type::BaseModel
        # @!attribute arguments
        #   A JSON string of the arguments to pass to the function.
        #
        #   @return [String]
        required :arguments, String

        response_only do
          # @!attribute parsed
          #   The parsed contents of the arguments.
          #
          #   @return [Object, nil]
          required :parsed, OpenAI::StructuredOutput::ParsedJson
        end

        # @!attribute call_id
        #   The unique ID of the function tool call generated by the model.
        #
        #   @return [String]
        required :call_id, String

        # @!attribute name
        #   The name of the function to run.
        #
        #   @return [String]
        required :name, String

        # @!attribute type
        #   The type of the function tool call. Always `function_call`.
        #
        #   @return [Symbol, :function_call]
        required :type, const: :function_call

        # @!attribute id
        #   The unique ID of the function tool call.
        #
        #   @return [String, nil]
        optional :id, String

        # @!attribute caller_
        #   The execution context that produced this tool call.
        #
        #   @return [OpenAI::Models::Responses::ResponseFunctionToolCall::Caller::Direct, OpenAI::Models::Responses::ResponseFunctionToolCall::Caller::Program, nil]
        optional(
          :caller_,
          union: -> { OpenAI::Responses::ResponseFunctionToolCall::Caller },
          api_name: :caller,
          nil?: true
        )

        # @!attribute namespace
        #   The namespace of the function to run.
        #
        #   @return [String, nil]
        optional :namespace, String

        # @!attribute status
        #   The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        #   Populated when items are returned via API.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseFunctionToolCall::Status, nil]
        optional :status, enum: -> { OpenAI::Responses::ResponseFunctionToolCall::Status }

        # @!method initialize(arguments:, call_id:, name:, id: nil, caller_: nil, namespace: nil, status: nil, type: :function_call)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Responses::ResponseFunctionToolCall} for more details.
        #
        #   A tool call to run a function. See the
        #   [function calling guide](https://platform.openai.com/docs/guides/function-calling)
        #   for more information.
        #
        #   @param arguments [String] A JSON string of the arguments to pass to the function.
        #
        #   @param call_id [String] The unique ID of the function tool call generated by the model.
        #
        #   @param name [String] The name of the function to run.
        #
        #   @param id [String] The unique ID of the function tool call.
        #
        #   @param caller_ [OpenAI::Models::Responses::ResponseFunctionToolCall::Caller::Direct, OpenAI::Models::Responses::ResponseFunctionToolCall::Caller::Program, nil] The execution context that produced this tool call.
        #
        #   @param namespace [String] The namespace of the function to run.
        #
        #   @param status [Symbol, OpenAI::Models::Responses::ResponseFunctionToolCall::Status] The status of the item. One of `in_progress`, `completed`, or
        #
        #   @param type [Symbol, :function_call] The type of the function tool call. Always `function_call`.

        # The execution context that produced this tool call.
        #
        # @see OpenAI::Models::Responses::ResponseFunctionToolCall#caller_
        module Caller
          extend OpenAI::Internal::Type::Union

          discriminator :type

          variant :direct, -> { OpenAI::Responses::ResponseFunctionToolCall::Caller::Direct }

          variant :program, -> { OpenAI::Responses::ResponseFunctionToolCall::Caller::Program }

          class Direct < OpenAI::Internal::Type::BaseModel
            # @!attribute type
            #
            #   @return [Symbol, :direct]
            required :type, const: :direct

            # @!method initialize(type: :direct)
            #   @param type [Symbol, :direct]
          end

          class Program < OpenAI::Internal::Type::BaseModel
            # @!attribute caller_id
            #   The call ID of the program item that produced this tool call.
            #
            #   @return [String]
            required :caller_id, String

            # @!attribute type
            #
            #   @return [Symbol, :program]
            required :type, const: :program

            # @!method initialize(caller_id:, type: :program)
            #   @param caller_id [String] The call ID of the program item that produced this tool call.
            #
            #   @param type [Symbol, :program]
          end

          # @!method self.variants
          #   @return [Array(OpenAI::Models::Responses::ResponseFunctionToolCall::Caller::Direct, OpenAI::Models::Responses::ResponseFunctionToolCall::Caller::Program)]
        end

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        #
        # @see OpenAI::Models::Responses::ResponseFunctionToolCall#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
