# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseApplyPatchToolCallOutput < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the apply patch tool call output. Populated when this item is
        #   returned via API.
        #
        #   @return [String]
        required :id, String

        # @!attribute call_id
        #   The unique ID of the apply patch tool call generated by the model.
        #
        #   @return [String]
        required :call_id, String

        # @!attribute status
        #   The status of the apply patch tool call output. One of `completed` or `failed`.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput::Status]
        required :status, enum: -> { OpenAI::Responses::ResponseApplyPatchToolCallOutput::Status }

        # @!attribute type
        #   The type of the item. Always `apply_patch_call_output`.
        #
        #   @return [Symbol, :apply_patch_call_output]
        required :type, const: :apply_patch_call_output

        # @!attribute caller_
        #   The execution context that produced this tool call.
        #
        #   @return [OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput::Caller::Direct, OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput::Caller::Program, nil]
        optional(
          :caller_,
          union: -> { OpenAI::Responses::ResponseApplyPatchToolCallOutput::Caller },
          api_name: :caller,
          nil?: true
        )

        # @!attribute created_by
        #   The ID of the entity that created this tool call output.
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!attribute output
        #   Optional textual output returned by the apply patch tool.
        #
        #   @return [String, nil]
        optional :output, String, nil?: true

        # @!method initialize(id:, call_id:, status:, caller_: nil, created_by: nil, output: nil, type: :apply_patch_call_output)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput} for more details.
        #
        #   The output emitted by an apply patch tool call.
        #
        #   @param id [String] The unique ID of the apply patch tool call output. Populated when this item is r
        #
        #   @param call_id [String] The unique ID of the apply patch tool call generated by the model.
        #
        #   @param status [Symbol, OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput::Status] The status of the apply patch tool call output. One of `completed` or `failed`.
        #
        #   @param caller_ [OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput::Caller::Direct, OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput::Caller::Program, nil] The execution context that produced this tool call.
        #
        #   @param created_by [String] The ID of the entity that created this tool call output.
        #
        #   @param output [String, nil] Optional textual output returned by the apply patch tool.
        #
        #   @param type [Symbol, :apply_patch_call_output] The type of the item. Always `apply_patch_call_output`.

        # The status of the apply patch tool call output. One of `completed` or `failed`.
        #
        # @see OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput#status
        module Status
          extend OpenAI::Internal::Type::Enum

          COMPLETED = :completed
          FAILED = :failed

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # The execution context that produced this tool call.
        #
        # @see OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput#caller_
        module Caller
          extend OpenAI::Internal::Type::Union

          discriminator :type

          variant :direct, -> { OpenAI::Responses::ResponseApplyPatchToolCallOutput::Caller::Direct }

          variant :program, -> { OpenAI::Responses::ResponseApplyPatchToolCallOutput::Caller::Program }

          class Direct < OpenAI::Internal::Type::BaseModel
            # @!attribute type
            #
            #   @return [Symbol, :direct]
            required :type, const: :direct

            # @!method initialize(type: :direct)
            #   @param type [Symbol, :direct]
          end

          class Program < OpenAI::Internal::Type::BaseModel
            # @!attribute caller_id
            #   The call ID of the program item that produced this tool call.
            #
            #   @return [String]
            required :caller_id, String

            # @!attribute type
            #
            #   @return [Symbol, :program]
            required :type, const: :program

            # @!method initialize(caller_id:, type: :program)
            #   @param caller_id [String] The call ID of the program item that produced this tool call.
            #
            #   @param type [Symbol, :program]
          end

          # @!method self.variants
          #   @return [Array(OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput::Caller::Direct, OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput::Caller::Program)]
        end
      end
    end
  end
end
