# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseToolSearchOutputItemParam < OpenAI::Internal::Type::BaseModel
        # @!attribute tools
        #   The loaded tool definitions returned by the tool search output.
        #
        #   @return [Array<OpenAI::Models::Responses::FunctionTool, OpenAI::Models::Responses::FileSearchTool, OpenAI::Models::Responses::ComputerTool, OpenAI::Models::Responses::ComputerUsePreviewTool, OpenAI::Models::Responses::Tool::Mcp, OpenAI::Models::Responses::Tool::CodeInterpreter, OpenAI::Models::Responses::Tool::ProgrammaticToolCalling, OpenAI::Models::Responses::Tool::ImageGeneration, OpenAI::Models::Responses::Tool::LocalShell, OpenAI::Models::Responses::FunctionShellTool, OpenAI::Models::Responses::CustomTool, OpenAI::Models::Responses::NamespaceTool, OpenAI::Models::Responses::ToolSearchTool, OpenAI::Models::Responses::ApplyPatchTool, OpenAI::Models::Responses::WebSearchTool, OpenAI::Models::Responses::WebSearchPreviewTool>]
        required :tools, -> { OpenAI::Internal::Type::ArrayOf[union: OpenAI::Responses::Tool] }

        # @!attribute type
        #   The item type. Always `tool_search_output`.
        #
        #   @return [Symbol, :tool_search_output]
        required :type, const: :tool_search_output

        # @!attribute id
        #   The unique ID of this tool search output.
        #
        #   @return [String, nil]
        optional :id, String, nil?: true

        # @!attribute call_id
        #   The unique ID of the tool search call generated by the model.
        #
        #   @return [String, nil]
        optional :call_id, String, nil?: true

        # @!attribute execution
        #   Whether tool search was executed by the server or by the client.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseToolSearchOutputItemParam::Execution, nil]
        optional :execution, enum: -> { OpenAI::Responses::ResponseToolSearchOutputItemParam::Execution }

        # @!attribute status
        #   The status of the tool search output.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseToolSearchOutputItemParam::Status, nil]
        optional(
          :status,
          enum: -> {
            OpenAI::Responses::ResponseToolSearchOutputItemParam::Status
          },
          nil?: true
        )

        # @!method initialize(tools:, id: nil, call_id: nil, execution: nil, status: nil, type: :tool_search_output)
        #   @param tools [Array<OpenAI::Models::Responses::FunctionTool, OpenAI::Models::Responses::FileSearchTool, OpenAI::Models::Responses::ComputerTool, OpenAI::Models::Responses::ComputerUsePreviewTool, OpenAI::Models::Responses::Tool::Mcp, OpenAI::Models::Responses::Tool::CodeInterpreter, OpenAI::Models::Responses::Tool::ProgrammaticToolCalling, OpenAI::Models::Responses::Tool::ImageGeneration, OpenAI::Models::Responses::Tool::LocalShell, OpenAI::Models::Responses::FunctionShellTool, OpenAI::Models::Responses::CustomTool, OpenAI::Models::Responses::NamespaceTool, OpenAI::Models::Responses::ToolSearchTool, OpenAI::Models::Responses::ApplyPatchTool, OpenAI::Models::Responses::WebSearchTool, OpenAI::Models::Responses::WebSearchPreviewTool>] The loaded tool definitions returned by the tool search output.
        #
        #   @param id [String, nil] The unique ID of this tool search output.
        #
        #   @param call_id [String, nil] The unique ID of the tool search call generated by the model.
        #
        #   @param execution [Symbol, OpenAI::Models::Responses::ResponseToolSearchOutputItemParam::Execution] Whether tool search was executed by the server or by the client.
        #
        #   @param status [Symbol, OpenAI::Models::Responses::ResponseToolSearchOutputItemParam::Status, nil] The status of the tool search output.
        #
        #   @param type [Symbol, :tool_search_output] The item type. Always `tool_search_output`.

        # Whether tool search was executed by the server or by the client.
        #
        # @see OpenAI::Models::Responses::ResponseToolSearchOutputItemParam#execution
        module Execution
          extend OpenAI::Internal::Type::Enum

          SERVER = :server
          CLIENT = :client

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # The status of the tool search output.
        #
        # @see OpenAI::Models::Responses::ResponseToolSearchOutputItemParam#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
