# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseFunctionShellToolCall < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the shell tool call. Populated when this item is returned via
        #   API.
        #
        #   @return [String]
        required :id, String

        # @!attribute action
        #   The shell commands and limits that describe how to run the tool call.
        #
        #   @return [OpenAI::Models::Responses::ResponseFunctionShellToolCall::Action]
        required :action, -> { OpenAI::Responses::ResponseFunctionShellToolCall::Action }

        # @!attribute call_id
        #   The unique ID of the shell tool call generated by the model.
        #
        #   @return [String]
        required :call_id, String

        # @!attribute environment
        #   Represents the use of a local environment to perform shell actions.
        #
        #   @return [OpenAI::Models::Responses::ResponseLocalEnvironment, OpenAI::Models::Responses::ResponseContainerReference, nil]
        required(
          :environment,
          union: -> { OpenAI::Responses::ResponseFunctionShellToolCall::Environment },
          nil?: true
        )

        # @!attribute status
        #   The status of the shell call. One of `in_progress`, `completed`, or
        #   `incomplete`.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseFunctionShellToolCall::Status]
        required :status, enum: -> { OpenAI::Responses::ResponseFunctionShellToolCall::Status }

        # @!attribute type
        #   The type of the item. Always `shell_call`.
        #
        #   @return [Symbol, :shell_call]
        required :type, const: :shell_call

        # @!attribute caller_
        #   The execution context that produced this tool call.
        #
        #   @return [OpenAI::Models::Responses::ResponseFunctionShellToolCall::Caller::Direct, OpenAI::Models::Responses::ResponseFunctionShellToolCall::Caller::Program, nil]
        optional(
          :caller_,
          union: -> { OpenAI::Responses::ResponseFunctionShellToolCall::Caller },
          api_name: :caller,
          nil?: true
        )

        # @!attribute created_by
        #   The ID of the entity that created this tool call.
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!method initialize(id:, action:, call_id:, environment:, status:, caller_: nil, created_by: nil, type: :shell_call)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Responses::ResponseFunctionShellToolCall} for more details.
        #
        #   A tool call that executes one or more shell commands in a managed environment.
        #
        #   @param id [String] The unique ID of the shell tool call. Populated when this item is returned via A
        #
        #   @param action [OpenAI::Models::Responses::ResponseFunctionShellToolCall::Action] The shell commands and limits that describe how to run the tool call.
        #
        #   @param call_id [String] The unique ID of the shell tool call generated by the model.
        #
        #   @param environment [OpenAI::Models::Responses::ResponseLocalEnvironment, OpenAI::Models::Responses::ResponseContainerReference, nil] Represents the use of a local environment to perform shell actions.
        #
        #   @param status [Symbol, OpenAI::Models::Responses::ResponseFunctionShellToolCall::Status] The status of the shell call. One of `in_progress`, `completed`, or `incomplete`
        #
        #   @param caller_ [OpenAI::Models::Responses::ResponseFunctionShellToolCall::Caller::Direct, OpenAI::Models::Responses::ResponseFunctionShellToolCall::Caller::Program, nil] The execution context that produced this tool call.
        #
        #   @param created_by [String] The ID of the entity that created this tool call.
        #
        #   @param type [Symbol, :shell_call] The type of the item. Always `shell_call`.

        # @see OpenAI::Models::Responses::ResponseFunctionShellToolCall#action
        class Action < OpenAI::Internal::Type::BaseModel
          # @!attribute commands
          #
          #   @return [Array<String>]
          required :commands, OpenAI::Internal::Type::ArrayOf[String]

          # @!attribute max_output_length
          #   Optional maximum number of characters to return from each command.
          #
          #   @return [Integer, nil]
          required :max_output_length, Integer, nil?: true

          # @!attribute timeout_ms
          #   Optional timeout in milliseconds for the commands.
          #
          #   @return [Integer, nil]
          required :timeout_ms, Integer, nil?: true

          # @!method initialize(commands:, max_output_length:, timeout_ms:)
          #   The shell commands and limits that describe how to run the tool call.
          #
          #   @param commands [Array<String>]
          #
          #   @param max_output_length [Integer, nil] Optional maximum number of characters to return from each command.
          #
          #   @param timeout_ms [Integer, nil] Optional timeout in milliseconds for the commands.
        end

        # Represents the use of a local environment to perform shell actions.
        #
        # @see OpenAI::Models::Responses::ResponseFunctionShellToolCall#environment
        module Environment
          extend OpenAI::Internal::Type::Union

          discriminator :type

          # Represents the use of a local environment to perform shell actions.
          variant :local, -> { OpenAI::Responses::ResponseLocalEnvironment }

          # Represents a container created with /v1/containers.
          variant :container_reference, -> { OpenAI::Responses::ResponseContainerReference }

          # @!method self.variants
          #   @return [Array(OpenAI::Models::Responses::ResponseLocalEnvironment, OpenAI::Models::Responses::ResponseContainerReference)]
        end

        # The status of the shell call. One of `in_progress`, `completed`, or
        # `incomplete`.
        #
        # @see OpenAI::Models::Responses::ResponseFunctionShellToolCall#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # The execution context that produced this tool call.
        #
        # @see OpenAI::Models::Responses::ResponseFunctionShellToolCall#caller_
        module Caller
          extend OpenAI::Internal::Type::Union

          discriminator :type

          variant :direct, -> { OpenAI::Responses::ResponseFunctionShellToolCall::Caller::Direct }

          variant :program, -> { OpenAI::Responses::ResponseFunctionShellToolCall::Caller::Program }

          class Direct < OpenAI::Internal::Type::BaseModel
            # @!attribute type
            #
            #   @return [Symbol, :direct]
            required :type, const: :direct

            # @!method initialize(type: :direct)
            #   @param type [Symbol, :direct]
          end

          class Program < OpenAI::Internal::Type::BaseModel
            # @!attribute caller_id
            #   The call ID of the program item that produced this tool call.
            #
            #   @return [String]
            required :caller_id, String

            # @!attribute type
            #
            #   @return [Symbol, :program]
            required :type, const: :program

            # @!method initialize(caller_id:, type: :program)
            #   @param caller_id [String] The call ID of the program item that produced this tool call.
            #
            #   @param type [Symbol, :program]
          end

          # @!method self.variants
          #   @return [Array(OpenAI::Models::Responses::ResponseFunctionShellToolCall::Caller::Direct, OpenAI::Models::Responses::ResponseFunctionShellToolCall::Caller::Program)]
        end
      end
    end
  end
end
