# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      # @see OpenAI::Resources::Responses#create
      #
      # @see OpenAI::Resources::Responses#stream_raw
      class Response < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   Unique identifier for this Response.
        #
        #   @return [String]
        required :id, String

        # @!attribute created_at
        #   Unix timestamp (in seconds) of when this Response was created.
        #
        #   @return [Float]
        required :created_at, Float

        # @!attribute error
        #   An error object returned when the model fails to generate a Response.
        #
        #   @return [OpenAI::Models::Responses::ResponseError, nil]
        required :error, -> { OpenAI::Responses::ResponseError }, nil?: true

        # @!attribute incomplete_details
        #   Details about why the response is incomplete.
        #
        #   @return [OpenAI::Models::Responses::Response::IncompleteDetails, nil]
        required :incomplete_details, -> { OpenAI::Responses::Response::IncompleteDetails }, nil?: true

        # @!attribute instructions
        #   A system (or developer) message inserted into the model's context.
        #
        #   When using along with `previous_response_id`, the instructions from a previous
        #   response will not be carried over to the next response. This makes it simple to
        #   swap out system (or developer) messages in new responses.
        #
        #   @return [String, Array<OpenAI::Models::Responses::EasyInputMessage, OpenAI::Models::Responses::ResponseInputItem::Message, OpenAI::Models::Responses::ResponseOutputMessage, OpenAI::Models::Responses::ResponseFileSearchToolCall, OpenAI::Models::Responses::ResponseComputerToolCall, OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput, OpenAI::Models::Responses::ResponseFunctionWebSearch, OpenAI::Models::Responses::ResponseFunctionToolCall, OpenAI::Models::Responses::ResponseInputItem::FunctionCallOutput, OpenAI::Models::Responses::ResponseInputItem::ToolSearchCall, OpenAI::Models::Responses::ResponseToolSearchOutputItemParam, OpenAI::Models::Responses::ResponseInputItem::AdditionalTools, OpenAI::Models::Responses::ResponseReasoningItem, OpenAI::Models::Responses::ResponseCompactionItemParam, OpenAI::Models::Responses::ResponseInputItem::ImageGenerationCall, OpenAI::Models::Responses::ResponseCodeInterpreterToolCall, OpenAI::Models::Responses::ResponseInputItem::LocalShellCall, OpenAI::Models::Responses::ResponseInputItem::LocalShellCallOutput, OpenAI::Models::Responses::ResponseInputItem::ShellCall, OpenAI::Models::Responses::ResponseInputItem::ShellCallOutput, OpenAI::Models::Responses::ResponseInputItem::ApplyPatchCall, OpenAI::Models::Responses::ResponseInputItem::ApplyPatchCallOutput, OpenAI::Models::Responses::ResponseInputItem::McpListTools, OpenAI::Models::Responses::ResponseInputItem::McpApprovalRequest, OpenAI::Models::Responses::ResponseInputItem::McpApprovalResponse, OpenAI::Models::Responses::ResponseInputItem::McpCall, OpenAI::Models::Responses::ResponseCustomToolCallOutput, OpenAI::Models::Responses::ResponseCustomToolCall, OpenAI::Models::Responses::ResponseInputItem::CompactionTrigger, OpenAI::Models::Responses::ResponseInputItem::ItemReference, OpenAI::Models::Responses::ResponseInputItem::Program, OpenAI::Models::Responses::ResponseInputItem::ProgramOutput>, nil]
        required :instructions, union: -> { OpenAI::Responses::Response::Instructions }, nil?: true

        # @!attribute metadata
        #   Set of 16 key-value pairs that can be attached to an object. This can be useful
        #   for storing additional information about the object in a structured format, and
        #   querying for objects via API or the dashboard.
        #
        #   Keys are strings with a maximum length of 64 characters. Values are strings with
        #   a maximum length of 512 characters.
        #
        #   @return [Hash{Symbol=>String}, nil]
        required :metadata, OpenAI::Internal::Type::HashOf[String], nil?: true

        # @!attribute model
        #   Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI offers a
        #   wide range of models with different capabilities, performance characteristics,
        #   and price points. Refer to the
        #   [model guide](https://platform.openai.com/docs/models) to browse and compare
        #   available models.
        #
        #   @return [String, Symbol, OpenAI::Models::ChatModel, OpenAI::Models::ResponsesModel::ResponsesOnlyModel]
        required :model, union: -> { OpenAI::ResponsesModel }

        # @!attribute object
        #   The object type of this resource - always set to `response`.
        #
        #   @return [Symbol, :response]
        required :object, const: :response

        # @!attribute output
        #   An array of content items generated by the model.
        #
        #   - The length and order of items in the `output` array is dependent on the
        #     model's response.
        #   - Rather than accessing the first item in the `output` array and assuming it's
        #     an `assistant` message with the content generated by the model, you might
        #     consider using the `output_text` property where supported in SDKs.
        #
        #   @return [Array<OpenAI::Models::Responses::ResponseOutputMessage, OpenAI::Models::Responses::ResponseFileSearchToolCall, OpenAI::Models::Responses::ResponseFunctionToolCall, OpenAI::Models::Responses::ResponseFunctionToolCallOutputItem, OpenAI::Models::Responses::ResponseFunctionWebSearch, OpenAI::Models::Responses::ResponseComputerToolCall, OpenAI::Models::Responses::ResponseComputerToolCallOutputItem, OpenAI::Models::Responses::ResponseReasoningItem, OpenAI::Models::Responses::ResponseOutputItem::Program, OpenAI::Models::Responses::ResponseOutputItem::ProgramOutput, OpenAI::Models::Responses::ResponseToolSearchCall, OpenAI::Models::Responses::ResponseToolSearchOutputItem, OpenAI::Models::Responses::ResponseOutputItem::AdditionalTools, OpenAI::Models::Responses::ResponseCompactionItem, OpenAI::Models::Responses::ResponseOutputItem::ImageGenerationCall, OpenAI::Models::Responses::ResponseCodeInterpreterToolCall, OpenAI::Models::Responses::ResponseOutputItem::LocalShellCall, OpenAI::Models::Responses::ResponseOutputItem::LocalShellCallOutput, OpenAI::Models::Responses::ResponseFunctionShellToolCall, OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput, OpenAI::Models::Responses::ResponseApplyPatchToolCall, OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput, OpenAI::Models::Responses::ResponseOutputItem::McpCall, OpenAI::Models::Responses::ResponseOutputItem::McpListTools, OpenAI::Models::Responses::ResponseOutputItem::McpApprovalRequest, OpenAI::Models::Responses::ResponseOutputItem::McpApprovalResponse, OpenAI::Models::Responses::ResponseCustomToolCall, OpenAI::Models::Responses::ResponseCustomToolCallOutputItem>]
        required :output, -> { OpenAI::Internal::Type::ArrayOf[union: OpenAI::Responses::ResponseOutputItem] }

        # @!attribute parallel_tool_calls
        #   Whether to allow the model to run tool calls in parallel.
        #
        #   @return [Boolean]
        required :parallel_tool_calls, OpenAI::Internal::Type::Boolean

        # @!attribute temperature
        #   What sampling temperature to use, between 0 and 2. Higher values like 0.8 will
        #   make the output more random, while lower values like 0.2 will make it more
        #   focused and deterministic. We generally recommend altering this or `top_p` but
        #   not both.
        #
        #   @return [Float, nil]
        required :temperature, Float, nil?: true

        # @!attribute tool_choice
        #   How the model should select which tool (or tools) to use when generating a
        #   response. See the `tools` parameter to see how to specify which tools the model
        #   can call.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ToolChoiceOptions, OpenAI::Models::Responses::ToolChoiceAllowed, OpenAI::Models::Responses::ToolChoiceTypes, OpenAI::Models::Responses::ToolChoiceFunction, OpenAI::Models::Responses::ToolChoiceMcp, OpenAI::Models::Responses::ToolChoiceCustom, OpenAI::Models::Responses::Response::ToolChoice::SpecificProgrammaticToolCallingParam, OpenAI::Models::Responses::ToolChoiceApplyPatch, OpenAI::Models::Responses::ToolChoiceShell]
        required :tool_choice, union: -> { OpenAI::Responses::Response::ToolChoice }

        # @!attribute tools
        #   An array of tools the model may call while generating a response. You can
        #   specify which tool to use by setting the `tool_choice` parameter.
        #
        #   We support the following categories of tools:
        #
        #   - **Built-in tools**: Tools that are provided by OpenAI that extend the model's
        #     capabilities, like
        #     [web search](https://platform.openai.com/docs/guides/tools-web-search) or
        #     [file search](https://platform.openai.com/docs/guides/tools-file-search).
        #     Learn more about
        #     [built-in tools](https://platform.openai.com/docs/guides/tools).
        #   - **MCP Tools**: Integrations with third-party systems via custom MCP servers or
        #     predefined connectors such as Google Drive and SharePoint. Learn more about
        #     [MCP Tools](https://platform.openai.com/docs/guides/tools-connectors-mcp).
        #   - **Function calls (custom tools)**: Functions that are defined by you, enabling
        #     the model to call your own code with strongly typed arguments and outputs.
        #     Learn more about
        #     [function calling](https://platform.openai.com/docs/guides/function-calling).
        #     You can also use custom tools to call your own code.
        #
        #   @return [Array<OpenAI::Models::Responses::FunctionTool, OpenAI::Models::Responses::FileSearchTool, OpenAI::Models::Responses::ComputerTool, OpenAI::Models::Responses::ComputerUsePreviewTool, OpenAI::Models::Responses::Tool::Mcp, OpenAI::Models::Responses::Tool::CodeInterpreter, OpenAI::Models::Responses::Tool::ProgrammaticToolCalling, OpenAI::Models::Responses::Tool::ImageGeneration, OpenAI::Models::Responses::Tool::LocalShell, OpenAI::Models::Responses::FunctionShellTool, OpenAI::Models::Responses::CustomTool, OpenAI::Models::Responses::NamespaceTool, OpenAI::Models::Responses::ToolSearchTool, OpenAI::Models::Responses::ApplyPatchTool, OpenAI::Models::Responses::WebSearchTool, OpenAI::Models::Responses::WebSearchPreviewTool>]
        required :tools, -> { OpenAI::Internal::Type::ArrayOf[union: OpenAI::Responses::Tool] }

        # @!attribute top_p
        #   An alternative to sampling with temperature, called nucleus sampling, where the
        #   model considers the results of the tokens with top_p probability mass. So 0.1
        #   means only the tokens comprising the top 10% probability mass are considered.
        #
        #   We generally recommend altering this or `temperature` but not both.
        #
        #   @return [Float, nil]
        required :top_p, Float, nil?: true

        # @!attribute background
        #   Whether to run the model response in the background.
        #   [Learn more](https://platform.openai.com/docs/guides/background).
        #
        #   @return [Boolean, nil]
        optional :background, OpenAI::Internal::Type::Boolean, nil?: true

        # @!attribute completed_at
        #   Unix timestamp (in seconds) of when this Response was completed. Only present
        #   when the status is `completed`.
        #
        #   @return [Float, nil]
        optional :completed_at, Float, nil?: true

        # @!attribute conversation
        #   The conversation that this response belonged to. Input items and output items
        #   from this response were automatically added to this conversation.
        #
        #   @return [OpenAI::Models::Responses::Response::Conversation, nil]
        optional :conversation, -> { OpenAI::Responses::Response::Conversation }, nil?: true

        # @!attribute max_output_tokens
        #   An upper bound for the number of tokens that can be generated for a response,
        #   including visible output tokens and
        #   [reasoning tokens](https://platform.openai.com/docs/guides/reasoning).
        #
        #   @return [Integer, nil]
        optional :max_output_tokens, Integer, nil?: true

        # @!attribute max_tool_calls
        #   The maximum number of total calls to built-in tools that can be processed in a
        #   response. This maximum number applies across all built-in tool calls, not per
        #   individual tool. Any further attempts to call a tool by the model will be
        #   ignored.
        #
        #   @return [Integer, nil]
        optional :max_tool_calls, Integer, nil?: true

        # @!attribute moderation
        #   Moderation results for the response input and output, if moderated completions
        #   were requested.
        #
        #   @return [OpenAI::Models::Responses::Response::Moderation, nil]
        optional :moderation, -> { OpenAI::Responses::Response::Moderation }, nil?: true

        # @!attribute previous_response_id
        #   The unique ID of the previous response to the model. Use this to create
        #   multi-turn conversations. Learn more about
        #   [conversation state](https://platform.openai.com/docs/guides/conversation-state).
        #   Cannot be used in conjunction with `conversation`.
        #
        #   @return [String, nil]
        optional :previous_response_id, String, nil?: true

        # @!attribute prompt
        #   Reference to a prompt template and its variables.
        #   [Learn more](https://platform.openai.com/docs/guides/text?api-mode=responses#reusable-prompts).
        #
        #   @return [OpenAI::Models::Responses::ResponsePrompt, nil]
        optional :prompt, -> { OpenAI::Responses::ResponsePrompt }, nil?: true

        # @!attribute prompt_cache_key
        #   Used by OpenAI to cache responses for similar requests to optimize your cache
        #   hit rates. Replaces the `user` field.
        #   [Learn more](https://platform.openai.com/docs/guides/prompt-caching).
        #
        #   @return [String, nil]
        optional :prompt_cache_key, String, nil?: true

        # @!attribute prompt_cache_options
        #   The prompt-caching options that were applied to the response. Supported for
        #   `gpt-5.6` and later models.
        #
        #   @return [OpenAI::Models::Responses::Response::PromptCacheOptions, nil]
        optional :prompt_cache_options, -> { OpenAI::Responses::Response::PromptCacheOptions }

        # @!attribute prompt_cache_retention
        #   @deprecated
        #
        #   Deprecated. Use `prompt_cache_options.ttl` instead.
        #
        #   The retention policy for the prompt cache. Set to `24h` to enable extended
        #   prompt caching, which keeps cached prefixes active for longer, up to a maximum
        #   of 24 hours.
        #   [Learn more](https://platform.openai.com/docs/guides/prompt-caching#prompt-cache-retention).
        #   This field expresses a maximum retention policy, while
        #   `prompt_cache_options.ttl` expresses a minimum cache lifetime. The two fields
        #   are independent and do not interact. For `gpt-5.5`, `gpt-5.5-pro`, and future
        #   models, only `24h` is supported.
        #
        #   For older models that support both `in_memory` and `24h`, the default depends on
        #   your organization's data retention policy:
        #
        #   - Organizations without ZDR enabled default to `24h`.
        #   - Organizations with ZDR enabled default to `in_memory` when
        #     `prompt_cache_retention` is not specified.
        #
        #   @return [Symbol, OpenAI::Models::Responses::Response::PromptCacheRetention, nil]
        optional(
          :prompt_cache_retention,
          enum: -> { OpenAI::Responses::Response::PromptCacheRetention },
          nil?: true
        )

        # @!attribute reasoning
        #   **gpt-5 and o-series models only**
        #
        #   Configuration options for
        #   [reasoning models](https://platform.openai.com/docs/guides/reasoning).
        #
        #   @return [OpenAI::Models::Reasoning, nil]
        optional :reasoning, -> { OpenAI::Reasoning }, nil?: true

        # @!attribute safety_identifier
        #   A stable identifier used to help detect users of your application that may be
        #   violating OpenAI's usage policies. The IDs should be a string that uniquely
        #   identifies each user, with a maximum length of 64 characters. We recommend
        #   hashing their username or email address, in order to avoid sending us any
        #   identifying information.
        #   [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#safety-identifiers).
        #
        #   @return [String, nil]
        optional :safety_identifier, String, nil?: true

        # @!attribute service_tier
        #   Specifies the processing type used for serving the request.
        #
        #   - If set to 'auto', then the request will be processed with the service tier
        #     configured in the Project settings. Unless otherwise configured, the Project
        #     will use 'default'.
        #   - If set to 'default', then the request will be processed with the standard
        #     pricing and performance for the selected model.
        #   - If set to '[flex](https://platform.openai.com/docs/guides/flex-processing)',
        #     then the request will be processed with the Flex Processing service tier.
        #   - To opt-in to [Fast mode](/api/docs/guides/fast-mode) at the request level,
        #     include the `service_tier=fast` or `service_tier=priority` parameter for
        #     Responses or Chat Completions. The response will show `service_tier=priority`
        #     regardless of if you specify `service_tier=fast` or `priority` in your
        #     request.
        #   - If set to 'ultrafast', then the request will be processed with the
        #     access-controlled Ultrafast Processing service tier. This tier is currently
        #     available for `gpt-5.6-sol`; a response served through it will show
        #     `service_tier=ultrafast`.
        #   - When not set, the default behavior is 'auto'.
        #
        #   When the `service_tier` parameter is set, the response body will include the
        #   `service_tier` value based on the processing mode actually used to serve the
        #   request. This response value may be different from the value set in the
        #   parameter.
        #
        #   @return [Symbol, OpenAI::Models::Responses::Response::ServiceTier, nil]
        optional :service_tier, enum: -> { OpenAI::Responses::Response::ServiceTier }, nil?: true

        # @!attribute status
        #   The status of the response generation. One of `completed`, `failed`,
        #   `in_progress`, `cancelled`, `queued`, or `incomplete`.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseStatus, nil]
        optional :status, enum: -> { OpenAI::Responses::ResponseStatus }

        # @!attribute text
        #   Configuration options for a text response from the model. Can be plain text or
        #   structured JSON data. Learn more:
        #
        #   - [Text inputs and outputs](https://platform.openai.com/docs/guides/text)
        #   - [Structured Outputs](https://platform.openai.com/docs/guides/structured-outputs)
        #
        #   @return [OpenAI::Models::Responses::ResponseTextConfig, nil]
        optional :text, -> { OpenAI::Responses::ResponseTextConfig }

        # @!attribute top_logprobs
        #   An integer between 0 and 20 specifying the maximum number of most likely tokens
        #   to return at each token position, each with an associated log probability. In
        #   some cases, the number of returned tokens may be fewer than requested.
        #
        #   @return [Integer, nil]
        optional :top_logprobs, Integer, nil?: true

        # @!attribute truncation
        #   The truncation strategy to use for the model response.
        #
        #   - `auto`: If the input to this Response exceeds the model's context window size,
        #     the model will truncate the response to fit the context window by dropping
        #     items from the beginning of the conversation.
        #   - `disabled` (default): If the input size will exceed the context window size
        #     for a model, the request will fail with a 400 error.
        #
        #   @return [Symbol, OpenAI::Models::Responses::Response::Truncation, nil]
        optional :truncation, enum: -> { OpenAI::Responses::Response::Truncation }, nil?: true

        # @!attribute usage
        #   Represents token usage details including input tokens, output tokens, a
        #   breakdown of output tokens, and the total tokens used.
        #
        #   @return [OpenAI::Models::Responses::ResponseUsage, nil]
        optional :usage, -> { OpenAI::Responses::ResponseUsage }

        # @!attribute user
        #   @deprecated
        #
        #   This field is being replaced by `safety_identifier` and `prompt_cache_key`. Use
        #   `prompt_cache_key` instead to maintain caching optimizations. A stable
        #   identifier for your end-users. Used to boost cache hit rates by better bucketing
        #   similar requests and to help OpenAI detect and prevent abuse.
        #   [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#safety-identifiers).
        #
        #   @return [String, nil]
        optional :user, String

        # Convenience property that aggregates all `output_text` items from the `output` list.
        #
        # If no `output_text` content blocks exist, then an empty string is returned.
        #
        # @return [String]
        def output_text
          texts = []

          output.each do |item|
            next unless item.type == :message
            item.content.each do |content|
              if content.type == :output_text
                texts << content.text
              end
            end
          end

          texts.join
        end

        # @!method initialize(id:, created_at:, error:, incomplete_details:, instructions:, metadata:, model:, output:, parallel_tool_calls:, temperature:, tool_choice:, tools:, top_p:, background: nil, completed_at: nil, conversation: nil, max_output_tokens: nil, max_tool_calls: nil, moderation: nil, previous_response_id: nil, prompt: nil, prompt_cache_key: nil, prompt_cache_options: nil, prompt_cache_retention: nil, reasoning: nil, safety_identifier: nil, service_tier: nil, status: nil, text: nil, top_logprobs: nil, truncation: nil, usage: nil, user: nil, object: :response)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Responses::Response} for more details.
        #
        #   @param id [String] Unique identifier for this Response.
        #
        #   @param created_at [Float] Unix timestamp (in seconds) of when this Response was created.
        #
        #   @param error [OpenAI::Models::Responses::ResponseError, nil] An error object returned when the model fails to generate a Response.
        #
        #   @param incomplete_details [OpenAI::Models::Responses::Response::IncompleteDetails, nil] Details about why the response is incomplete.
        #
        #   @param instructions [String, Array<OpenAI::Models::Responses::EasyInputMessage, OpenAI::Models::Responses::ResponseInputItem::Message, OpenAI::Models::Responses::ResponseOutputMessage, OpenAI::Models::Responses::ResponseFileSearchToolCall, OpenAI::Models::Responses::ResponseComputerToolCall, OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput, OpenAI::Models::Responses::ResponseFunctionWebSearch, OpenAI::Models::Responses::ResponseFunctionToolCall, OpenAI::Models::Responses::ResponseInputItem::FunctionCallOutput, OpenAI::Models::Responses::ResponseInputItem::ToolSearchCall, OpenAI::Models::Responses::ResponseToolSearchOutputItemParam, OpenAI::Models::Responses::ResponseInputItem::AdditionalTools, OpenAI::Models::Responses::ResponseReasoningItem, OpenAI::Models::Responses::ResponseCompactionItemParam, OpenAI::Models::Responses::ResponseInputItem::ImageGenerationCall, OpenAI::Models::Responses::ResponseCodeInterpreterToolCall, OpenAI::Models::Responses::ResponseInputItem::LocalShellCall, OpenAI::Models::Responses::ResponseInputItem::LocalShellCallOutput, OpenAI::Models::Responses::ResponseInputItem::ShellCall, OpenAI::Models::Responses::ResponseInputItem::ShellCallOutput, OpenAI::Models::Responses::ResponseInputItem::ApplyPatchCall, OpenAI::Models::Responses::ResponseInputItem::ApplyPatchCallOutput, OpenAI::Models::Responses::ResponseInputItem::McpListTools, OpenAI::Models::Responses::ResponseInputItem::McpApprovalRequest, OpenAI::Models::Responses::ResponseInputItem::McpApprovalResponse, OpenAI::Models::Responses::ResponseInputItem::McpCall, OpenAI::Models::Responses::ResponseCustomToolCallOutput, OpenAI::Models::Responses::ResponseCustomToolCall, OpenAI::Models::Responses::ResponseInputItem::CompactionTrigger, OpenAI::Models::Responses::ResponseInputItem::ItemReference, OpenAI::Models::Responses::ResponseInputItem::Program, OpenAI::Models::Responses::ResponseInputItem::ProgramOutput>, nil] A system (or developer) message inserted into the model's context.
        #
        #   @param metadata [Hash{Symbol=>String}, nil] Set of 16 key-value pairs that can be attached to an object. This can be
        #
        #   @param model [String, Symbol, OpenAI::Models::ChatModel, OpenAI::Models::ResponsesModel::ResponsesOnlyModel] Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI
        #
        #   @param output [Array<OpenAI::Models::Responses::ResponseOutputMessage, OpenAI::Models::Responses::ResponseFileSearchToolCall, OpenAI::Models::Responses::ResponseFunctionToolCall, OpenAI::Models::Responses::ResponseFunctionToolCallOutputItem, OpenAI::Models::Responses::ResponseFunctionWebSearch, OpenAI::Models::Responses::ResponseComputerToolCall, OpenAI::Models::Responses::ResponseComputerToolCallOutputItem, OpenAI::Models::Responses::ResponseReasoningItem, OpenAI::Models::Responses::ResponseOutputItem::Program, OpenAI::Models::Responses::ResponseOutputItem::ProgramOutput, OpenAI::Models::Responses::ResponseToolSearchCall, OpenAI::Models::Responses::ResponseToolSearchOutputItem, OpenAI::Models::Responses::ResponseOutputItem::AdditionalTools, OpenAI::Models::Responses::ResponseCompactionItem, OpenAI::Models::Responses::ResponseOutputItem::ImageGenerationCall, OpenAI::Models::Responses::ResponseCodeInterpreterToolCall, OpenAI::Models::Responses::ResponseOutputItem::LocalShellCall, OpenAI::Models::Responses::ResponseOutputItem::LocalShellCallOutput, OpenAI::Models::Responses::ResponseFunctionShellToolCall, OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput, OpenAI::Models::Responses::ResponseApplyPatchToolCall, OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput, OpenAI::Models::Responses::ResponseOutputItem::McpCall, OpenAI::Models::Responses::ResponseOutputItem::McpListTools, OpenAI::Models::Responses::ResponseOutputItem::McpApprovalRequest, OpenAI::Models::Responses::ResponseOutputItem::McpApprovalResponse, OpenAI::Models::Responses::ResponseCustomToolCall, OpenAI::Models::Responses::ResponseCustomToolCallOutputItem>] An array of content items generated by the model.
        #
        #   @param parallel_tool_calls [Boolean] Whether to allow the model to run tool calls in parallel.
        #
        #   @param temperature [Float, nil] What sampling temperature to use, between 0 and 2. Higher values like 0.8 will m
        #
        #   @param tool_choice [Symbol, OpenAI::Models::Responses::ToolChoiceOptions, OpenAI::Models::Responses::ToolChoiceAllowed, OpenAI::Models::Responses::ToolChoiceTypes, OpenAI::Models::Responses::ToolChoiceFunction, OpenAI::Models::Responses::ToolChoiceMcp, OpenAI::Models::Responses::ToolChoiceCustom, OpenAI::Models::Responses::Response::ToolChoice::SpecificProgrammaticToolCallingParam, OpenAI::Models::Responses::ToolChoiceApplyPatch, OpenAI::Models::Responses::ToolChoiceShell] How the model should select which tool (or tools) to use when generating
        #
        #   @param tools [Array<OpenAI::Models::Responses::FunctionTool, OpenAI::Models::Responses::FileSearchTool, OpenAI::Models::Responses::ComputerTool, OpenAI::Models::Responses::ComputerUsePreviewTool, OpenAI::Models::Responses::Tool::Mcp, OpenAI::Models::Responses::Tool::CodeInterpreter, OpenAI::Models::Responses::Tool::ProgrammaticToolCalling, OpenAI::Models::Responses::Tool::ImageGeneration, OpenAI::Models::Responses::Tool::LocalShell, OpenAI::Models::Responses::FunctionShellTool, OpenAI::Models::Responses::CustomTool, OpenAI::Models::Responses::NamespaceTool, OpenAI::Models::Responses::ToolSearchTool, OpenAI::Models::Responses::ApplyPatchTool, OpenAI::Models::Responses::WebSearchTool, OpenAI::Models::Responses::WebSearchPreviewTool>] An array of tools the model may call while generating a response. You
        #
        #   @param top_p [Float, nil] An alternative to sampling with temperature, called nucleus sampling,
        #
        #   @param background [Boolean, nil] Whether to run the model response in the background.
        #
        #   @param completed_at [Float, nil] Unix timestamp (in seconds) of when this Response was completed.
        #
        #   @param conversation [OpenAI::Models::Responses::Response::Conversation, nil] The conversation that this response belonged to. Input items and output items fr
        #
        #   @param max_output_tokens [Integer, nil] An upper bound for the number of tokens that can be generated for a response, in
        #
        #   @param max_tool_calls [Integer, nil] The maximum number of total calls to built-in tools that can be processed in a r
        #
        #   @param moderation [OpenAI::Models::Responses::Response::Moderation, nil] Moderation results for the response input and output, if moderated completions w
        #
        #   @param previous_response_id [String, nil] The unique ID of the previous response to the model. Use this to
        #
        #   @param prompt [OpenAI::Models::Responses::ResponsePrompt, nil] Reference to a prompt template and its variables.
        #
        #   @param prompt_cache_key [String, nil] Used by OpenAI to cache responses for similar requests to optimize your cache hi
        #
        #   @param prompt_cache_options [OpenAI::Models::Responses::Response::PromptCacheOptions] The prompt-caching options that were applied to the response. Supported for `gpt
        #
        #   @param prompt_cache_retention [Symbol, OpenAI::Models::Responses::Response::PromptCacheRetention, nil] Deprecated. Use `prompt_cache_options.ttl` instead.
        #
        #   @param reasoning [OpenAI::Models::Reasoning, nil] **gpt-5 and o-series models only**
        #
        #   @param safety_identifier [String, nil] A stable identifier used to help detect users of your application that may be vi
        #
        #   @param service_tier [Symbol, OpenAI::Models::Responses::Response::ServiceTier, nil] Specifies the processing type used for serving the request.
        #
        #   @param status [Symbol, OpenAI::Models::Responses::ResponseStatus] The status of the response generation. One of `completed`, `failed`,
        #
        #   @param text [OpenAI::Models::Responses::ResponseTextConfig] Configuration options for a text response from the model. Can be plain
        #
        #   @param top_logprobs [Integer, nil] An integer between 0 and 20 specifying the maximum number of most likely
        #
        #   @param truncation [Symbol, OpenAI::Models::Responses::Response::Truncation, nil] The truncation strategy to use for the model response.
        #
        #   @param usage [OpenAI::Models::Responses::ResponseUsage] Represents token usage details including input tokens, output tokens,
        #
        #   @param user [String] This field is being replaced by `safety_identifier` and `prompt_cache_key`. Use
        #
        #   @param object [Symbol, :response] The object type of this resource - always set to `response`.

        # @see OpenAI::Models::Responses::Response#incomplete_details
        class IncompleteDetails < OpenAI::Internal::Type::BaseModel
          # @!attribute reason
          #   The reason why the response is incomplete.
          #
          #   @return [Symbol, OpenAI::Models::Responses::Response::IncompleteDetails::Reason, nil]
          optional :reason, enum: -> { OpenAI::Responses::Response::IncompleteDetails::Reason }

          # @!method initialize(reason: nil)
          #   Details about why the response is incomplete.
          #
          #   @param reason [Symbol, OpenAI::Models::Responses::Response::IncompleteDetails::Reason] The reason why the response is incomplete.

          # The reason why the response is incomplete.
          #
          # @see OpenAI::Models::Responses::Response::IncompleteDetails#reason
          module Reason
            extend OpenAI::Internal::Type::Enum

            MAX_OUTPUT_TOKENS = :max_output_tokens
            CONTENT_FILTER = :content_filter

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        # A system (or developer) message inserted into the model's context.
        #
        # When using along with `previous_response_id`, the instructions from a previous
        # response will not be carried over to the next response. This makes it simple to
        # swap out system (or developer) messages in new responses.
        #
        # @see OpenAI::Models::Responses::Response#instructions
        module Instructions
          extend OpenAI::Internal::Type::Union

          # A text input to the model, equivalent to a text input with the
          # `developer` role.
          variant String

          # A list of one or many input items to the model, containing
          # different content types.
          variant -> { OpenAI::Models::Responses::Response::Instructions::ResponseInputItemArray }

          # @!method self.variants
          #   @return [Array(String, Array<OpenAI::Models::Responses::EasyInputMessage, OpenAI::Models::Responses::ResponseInputItem::Message, OpenAI::Models::Responses::ResponseOutputMessage, OpenAI::Models::Responses::ResponseFileSearchToolCall, OpenAI::Models::Responses::ResponseComputerToolCall, OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput, OpenAI::Models::Responses::ResponseFunctionWebSearch, OpenAI::Models::Responses::ResponseFunctionToolCall, OpenAI::Models::Responses::ResponseInputItem::FunctionCallOutput, OpenAI::Models::Responses::ResponseInputItem::ToolSearchCall, OpenAI::Models::Responses::ResponseToolSearchOutputItemParam, OpenAI::Models::Responses::ResponseInputItem::AdditionalTools, OpenAI::Models::Responses::ResponseReasoningItem, OpenAI::Models::Responses::ResponseCompactionItemParam, OpenAI::Models::Responses::ResponseInputItem::ImageGenerationCall, OpenAI::Models::Responses::ResponseCodeInterpreterToolCall, OpenAI::Models::Responses::ResponseInputItem::LocalShellCall, OpenAI::Models::Responses::ResponseInputItem::LocalShellCallOutput, OpenAI::Models::Responses::ResponseInputItem::ShellCall, OpenAI::Models::Responses::ResponseInputItem::ShellCallOutput, OpenAI::Models::Responses::ResponseInputItem::ApplyPatchCall, OpenAI::Models::Responses::ResponseInputItem::ApplyPatchCallOutput, OpenAI::Models::Responses::ResponseInputItem::McpListTools, OpenAI::Models::Responses::ResponseInputItem::McpApprovalRequest, OpenAI::Models::Responses::ResponseInputItem::McpApprovalResponse, OpenAI::Models::Responses::ResponseInputItem::McpCall, OpenAI::Models::Responses::ResponseCustomToolCallOutput, OpenAI::Models::Responses::ResponseCustomToolCall, OpenAI::Models::Responses::ResponseInputItem::CompactionTrigger, OpenAI::Models::Responses::ResponseInputItem::ItemReference, OpenAI::Models::Responses::ResponseInputItem::Program, OpenAI::Models::Responses::ResponseInputItem::ProgramOutput>)]

          # @type [OpenAI::Internal::Type::Converter]
          ResponseInputItemArray = OpenAI::Internal::Type::ArrayOf[union: -> { OpenAI::Responses::ResponseInputItem }]
        end

        # How the model should select which tool (or tools) to use when generating a
        # response. See the `tools` parameter to see how to specify which tools the model
        # can call.
        #
        # @see OpenAI::Models::Responses::Response#tool_choice
        module ToolChoice
          extend OpenAI::Internal::Type::Union

          # Controls which (if any) tool is called by the model.
          #
          # `none` means the model will not call any tool and instead generates a message.
          #
          # `auto` means the model can pick between generating a message or calling one or
          # more tools.
          #
          # `required` means the model must call one or more tools.
          variant enum: -> { OpenAI::Responses::ToolChoiceOptions }

          # Constrains the tools available to the model to a pre-defined set.
          variant -> { OpenAI::Responses::ToolChoiceAllowed }

          # Indicates that the model should use a built-in tool to generate a response.
          # [Learn more about built-in tools](https://platform.openai.com/docs/guides/tools).
          variant -> { OpenAI::Responses::ToolChoiceTypes }

          # Use this option to force the model to call a specific function.
          variant -> { OpenAI::Responses::ToolChoiceFunction }

          # Use this option to force the model to call a specific tool on a remote MCP server.
          variant -> { OpenAI::Responses::ToolChoiceMcp }

          # Use this option to force the model to call a specific custom tool.
          variant -> { OpenAI::Responses::ToolChoiceCustom }

          variant -> { OpenAI::Responses::Response::ToolChoice::SpecificProgrammaticToolCallingParam }

          # Forces the model to call the apply_patch tool when executing a tool call.
          variant -> { OpenAI::Responses::ToolChoiceApplyPatch }

          # Forces the model to call the shell tool when a tool call is required.
          variant -> { OpenAI::Responses::ToolChoiceShell }

          class SpecificProgrammaticToolCallingParam < OpenAI::Internal::Type::BaseModel
            # @!attribute type
            #   The tool to call. Always `programmatic_tool_calling`.
            #
            #   @return [Symbol, :programmatic_tool_calling]
            required :type, const: :programmatic_tool_calling

            # @!method initialize(type: :programmatic_tool_calling)
            #   @param type [Symbol, :programmatic_tool_calling] The tool to call. Always `programmatic_tool_calling`.
          end

          # @!method self.variants
          #   @return [Array(Symbol, OpenAI::Models::Responses::ToolChoiceOptions, OpenAI::Models::Responses::ToolChoiceAllowed, OpenAI::Models::Responses::ToolChoiceTypes, OpenAI::Models::Responses::ToolChoiceFunction, OpenAI::Models::Responses::ToolChoiceMcp, OpenAI::Models::Responses::ToolChoiceCustom, OpenAI::Models::Responses::Response::ToolChoice::SpecificProgrammaticToolCallingParam, OpenAI::Models::Responses::ToolChoiceApplyPatch, OpenAI::Models::Responses::ToolChoiceShell)]
        end

        # @see OpenAI::Models::Responses::Response#conversation
        class Conversation < OpenAI::Internal::Type::BaseModel
          # @!attribute id
          #   The unique ID of the conversation that this response was associated with.
          #
          #   @return [String]
          required :id, String

          # @!method initialize(id:)
          #   The conversation that this response belonged to. Input items and output items
          #   from this response were automatically added to this conversation.
          #
          #   @param id [String] The unique ID of the conversation that this response was associated with.
        end

        # @see OpenAI::Models::Responses::Response#moderation
        class Moderation < OpenAI::Internal::Type::BaseModel
          # @!attribute input
          #   Moderation for the response input.
          #
          #   @return [OpenAI::Models::Responses::Response::Moderation::Input::ModerationResult, OpenAI::Models::Responses::Response::Moderation::Input::Error]
          required :input, union: -> { OpenAI::Responses::Response::Moderation::Input }

          # @!attribute output
          #   Moderation for the response output.
          #
          #   @return [OpenAI::Models::Responses::Response::Moderation::Output::ModerationResult, OpenAI::Models::Responses::Response::Moderation::Output::Error]
          required :output, union: -> { OpenAI::Responses::Response::Moderation::Output }

          # @!method initialize(input:, output:)
          #   Moderation results for the response input and output, if moderated completions
          #   were requested.
          #
          #   @param input [OpenAI::Models::Responses::Response::Moderation::Input::ModerationResult, OpenAI::Models::Responses::Response::Moderation::Input::Error] Moderation for the response input.
          #
          #   @param output [OpenAI::Models::Responses::Response::Moderation::Output::ModerationResult, OpenAI::Models::Responses::Response::Moderation::Output::Error] Moderation for the response output.

          # Moderation for the response input.
          #
          # @see OpenAI::Models::Responses::Response::Moderation#input
          module Input
            extend OpenAI::Internal::Type::Union

            discriminator :type

            # A moderation result produced for the response input or output.
            variant :moderation_result, -> { OpenAI::Responses::Response::Moderation::Input::ModerationResult }

            # An error produced while attempting moderation for the response input or output.
            variant :error, -> { OpenAI::Responses::Response::Moderation::Input::Error }

            class ModerationResult < OpenAI::Internal::Type::BaseModel
              # @!attribute categories
              #   A dictionary of moderation categories to booleans, True if the input is flagged
              #   under this category.
              #
              #   @return [Hash{Symbol=>Boolean}]
              required :categories, OpenAI::Internal::Type::HashOf[OpenAI::Internal::Type::Boolean]

              # @!attribute category_applied_input_types
              #   Which modalities of input are reflected by the score for each category.
              #
              #   @return [Hash{Symbol=>Array<Symbol, OpenAI::Models::Responses::Response::Moderation::Input::ModerationResult::CategoryAppliedInputType>}]
              required(
                :category_applied_input_types,
                -> do
                  OpenAI::Internal::Type::HashOf[
                    OpenAI::Internal::Type::ArrayOf[
                      enum: OpenAI::Responses::Response::Moderation::Input::ModerationResult::CategoryAppliedInputType
                    ]
                  ]
                end
              )

              # @!attribute category_scores
              #   A dictionary of moderation categories to scores.
              #
              #   @return [Hash{Symbol=>Float}]
              required :category_scores, OpenAI::Internal::Type::HashOf[Float]

              # @!attribute flagged
              #   A boolean indicating whether the content was flagged by any category.
              #
              #   @return [Boolean]
              required :flagged, OpenAI::Internal::Type::Boolean

              # @!attribute model
              #   The moderation model that produced this result.
              #
              #   @return [String]
              required :model, String

              # @!attribute type
              #   The object type, which was always `moderation_result` for successful moderation
              #   results.
              #
              #   @return [Symbol, :moderation_result]
              required :type, const: :moderation_result

              # @!method initialize(categories:, category_applied_input_types:, category_scores:, flagged:, model:, type: :moderation_result)
              #   Some parameter documentations has been truncated, see
              #   {OpenAI::Models::Responses::Response::Moderation::Input::ModerationResult} for
              #   more details.
              #
              #   A moderation result produced for the response input or output.
              #
              #   @param categories [Hash{Symbol=>Boolean}] A dictionary of moderation categories to booleans, True if the input is flagged
              #
              #   @param category_applied_input_types [Hash{Symbol=>Array<Symbol, OpenAI::Models::Responses::Response::Moderation::Input::ModerationResult::CategoryAppliedInputType>}] Which modalities of input are reflected by the score for each category.
              #
              #   @param category_scores [Hash{Symbol=>Float}] A dictionary of moderation categories to scores.
              #
              #   @param flagged [Boolean] A boolean indicating whether the content was flagged by any category.
              #
              #   @param model [String] The moderation model that produced this result.
              #
              #   @param type [Symbol, :moderation_result] The object type, which was always `moderation_result` for successful moderation

              module CategoryAppliedInputType
                extend OpenAI::Internal::Type::Enum

                TEXT = :text
                IMAGE = :image

                # @!method self.values
                #   @return [Array<Symbol>]
              end
            end

            class Error < OpenAI::Internal::Type::BaseModel
              # @!attribute code
              #   The error code.
              #
              #   @return [String]
              required :code, String

              # @!attribute message
              #   The error message.
              #
              #   @return [String]
              required :message, String

              # @!attribute type
              #   The object type, which was always `error` for moderation failures.
              #
              #   @return [Symbol, :error]
              required :type, const: :error

              # @!method initialize(code:, message:, type: :error)
              #   An error produced while attempting moderation for the response input or output.
              #
              #   @param code [String] The error code.
              #
              #   @param message [String] The error message.
              #
              #   @param type [Symbol, :error] The object type, which was always `error` for moderation failures.
            end

            # @!method self.variants
            #   @return [Array(OpenAI::Models::Responses::Response::Moderation::Input::ModerationResult, OpenAI::Models::Responses::Response::Moderation::Input::Error)]
          end

          # Moderation for the response output.
          #
          # @see OpenAI::Models::Responses::Response::Moderation#output
          module Output
            extend OpenAI::Internal::Type::Union

            discriminator :type

            # A moderation result produced for the response input or output.
            variant :moderation_result, -> { OpenAI::Responses::Response::Moderation::Output::ModerationResult }

            # An error produced while attempting moderation for the response input or output.
            variant :error, -> { OpenAI::Responses::Response::Moderation::Output::Error }

            class ModerationResult < OpenAI::Internal::Type::BaseModel
              # @!attribute categories
              #   A dictionary of moderation categories to booleans, True if the input is flagged
              #   under this category.
              #
              #   @return [Hash{Symbol=>Boolean}]
              required :categories, OpenAI::Internal::Type::HashOf[OpenAI::Internal::Type::Boolean]

              # @!attribute category_applied_input_types
              #   Which modalities of input are reflected by the score for each category.
              #
              #   @return [Hash{Symbol=>Array<Symbol, OpenAI::Models::Responses::Response::Moderation::Output::ModerationResult::CategoryAppliedInputType>}]
              required(
                :category_applied_input_types,
                -> do
                  OpenAI::Internal::Type::HashOf[
                    OpenAI::Internal::Type::ArrayOf[
                      enum: OpenAI::Responses::Response::Moderation::Output::ModerationResult::CategoryAppliedInputType
                    ]
                  ]
                end
              )

              # @!attribute category_scores
              #   A dictionary of moderation categories to scores.
              #
              #   @return [Hash{Symbol=>Float}]
              required :category_scores, OpenAI::Internal::Type::HashOf[Float]

              # @!attribute flagged
              #   A boolean indicating whether the content was flagged by any category.
              #
              #   @return [Boolean]
              required :flagged, OpenAI::Internal::Type::Boolean

              # @!attribute model
              #   The moderation model that produced this result.
              #
              #   @return [String]
              required :model, String

              # @!attribute type
              #   The object type, which was always `moderation_result` for successful moderation
              #   results.
              #
              #   @return [Symbol, :moderation_result]
              required :type, const: :moderation_result

              # @!method initialize(categories:, category_applied_input_types:, category_scores:, flagged:, model:, type: :moderation_result)
              #   Some parameter documentations has been truncated, see
              #   {OpenAI::Models::Responses::Response::Moderation::Output::ModerationResult} for
              #   more details.
              #
              #   A moderation result produced for the response input or output.
              #
              #   @param categories [Hash{Symbol=>Boolean}] A dictionary of moderation categories to booleans, True if the input is flagged
              #
              #   @param category_applied_input_types [Hash{Symbol=>Array<Symbol, OpenAI::Models::Responses::Response::Moderation::Output::ModerationResult::CategoryAppliedInputType>}] Which modalities of input are reflected by the score for each category.
              #
              #   @param category_scores [Hash{Symbol=>Float}] A dictionary of moderation categories to scores.
              #
              #   @param flagged [Boolean] A boolean indicating whether the content was flagged by any category.
              #
              #   @param model [String] The moderation model that produced this result.
              #
              #   @param type [Symbol, :moderation_result] The object type, which was always `moderation_result` for successful moderation

              module CategoryAppliedInputType
                extend OpenAI::Internal::Type::Enum

                TEXT = :text
                IMAGE = :image

                # @!method self.values
                #   @return [Array<Symbol>]
              end
            end

            class Error < OpenAI::Internal::Type::BaseModel
              # @!attribute code
              #   The error code.
              #
              #   @return [String]
              required :code, String

              # @!attribute message
              #   The error message.
              #
              #   @return [String]
              required :message, String

              # @!attribute type
              #   The object type, which was always `error` for moderation failures.
              #
              #   @return [Symbol, :error]
              required :type, const: :error

              # @!method initialize(code:, message:, type: :error)
              #   An error produced while attempting moderation for the response input or output.
              #
              #   @param code [String] The error code.
              #
              #   @param message [String] The error message.
              #
              #   @param type [Symbol, :error] The object type, which was always `error` for moderation failures.
            end

            # @!method self.variants
            #   @return [Array(OpenAI::Models::Responses::Response::Moderation::Output::ModerationResult, OpenAI::Models::Responses::Response::Moderation::Output::Error)]
          end
        end

        # @see OpenAI::Models::Responses::Response#prompt_cache_options
        class PromptCacheOptions < OpenAI::Internal::Type::BaseModel
          # @!attribute mode
          #   Whether implicit prompt-cache breakpoints were enabled.
          #
          #   @return [Symbol, OpenAI::Models::Responses::Response::PromptCacheOptions::Mode]
          required :mode, enum: -> { OpenAI::Responses::Response::PromptCacheOptions::Mode }

          # @!attribute ttl
          #   The minimum lifetime applied to each cache breakpoint.
          #
          #   @return [Symbol, OpenAI::Models::Responses::Response::PromptCacheOptions::Ttl]
          required :ttl, enum: -> { OpenAI::Responses::Response::PromptCacheOptions::Ttl }

          # @!method initialize(mode:, ttl:)
          #   The prompt-caching options that were applied to the response. Supported for
          #   `gpt-5.6` and later models.
          #
          #   @param mode [Symbol, OpenAI::Models::Responses::Response::PromptCacheOptions::Mode] Whether implicit prompt-cache breakpoints were enabled.
          #
          #   @param ttl [Symbol, OpenAI::Models::Responses::Response::PromptCacheOptions::Ttl] The minimum lifetime applied to each cache breakpoint.

          # Whether implicit prompt-cache breakpoints were enabled.
          #
          # @see OpenAI::Models::Responses::Response::PromptCacheOptions#mode
          module Mode
            extend OpenAI::Internal::Type::Enum

            IMPLICIT = :implicit
            EXPLICIT = :explicit

            # @!method self.values
            #   @return [Array<Symbol>]
          end

          # The minimum lifetime applied to each cache breakpoint.
          #
          # @see OpenAI::Models::Responses::Response::PromptCacheOptions#ttl
          module Ttl
            extend OpenAI::Internal::Type::Enum

            TTL_30M = :"30m"

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        # @deprecated
        #
        # Deprecated. Use `prompt_cache_options.ttl` instead.
        #
        # The retention policy for the prompt cache. Set to `24h` to enable extended
        # prompt caching, which keeps cached prefixes active for longer, up to a maximum
        # of 24 hours.
        # [Learn more](https://platform.openai.com/docs/guides/prompt-caching#prompt-cache-retention).
        # This field expresses a maximum retention policy, while
        # `prompt_cache_options.ttl` expresses a minimum cache lifetime. The two fields
        # are independent and do not interact. For `gpt-5.5`, `gpt-5.5-pro`, and future
        # models, only `24h` is supported.
        #
        # For older models that support both `in_memory` and `24h`, the default depends on
        # your organization's data retention policy:
        #
        # - Organizations without ZDR enabled default to `24h`.
        # - Organizations with ZDR enabled default to `in_memory` when
        #   `prompt_cache_retention` is not specified.
        #
        # @see OpenAI::Models::Responses::Response#prompt_cache_retention
        module PromptCacheRetention
          extend OpenAI::Internal::Type::Enum

          IN_MEMORY = :in_memory
          PROMPT_CACHE_RETENTION_24H = :"24h"

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # Specifies the processing type used for serving the request.
        #
        # - If set to 'auto', then the request will be processed with the service tier
        #   configured in the Project settings. Unless otherwise configured, the Project
        #   will use 'default'.
        # - If set to 'default', then the request will be processed with the standard
        #   pricing and performance for the selected model.
        # - If set to '[flex](https://platform.openai.com/docs/guides/flex-processing)',
        #   then the request will be processed with the Flex Processing service tier.
        # - To opt-in to [Fast mode](/api/docs/guides/fast-mode) at the request level,
        #   include the `service_tier=fast` or `service_tier=priority` parameter for
        #   Responses or Chat Completions. The response will show `service_tier=priority`
        #   regardless of if you specify `service_tier=fast` or `priority` in your
        #   request.
        # - If set to 'ultrafast', then the request will be processed with the
        #   access-controlled Ultrafast Processing service tier. This tier is currently
        #   available for `gpt-5.6-sol`; a response served through it will show
        #   `service_tier=ultrafast`.
        # - When not set, the default behavior is 'auto'.
        #
        # When the `service_tier` parameter is set, the response body will include the
        # `service_tier` value based on the processing mode actually used to serve the
        # request. This response value may be different from the value set in the
        # parameter.
        #
        # @see OpenAI::Models::Responses::Response#service_tier
        module ServiceTier
          extend OpenAI::Internal::Type::Enum

          AUTO = :auto
          DEFAULT = :default
          FLEX = :flex
          SCALE = :scale
          PRIORITY = :priority
          FAST = :fast
          ULTRAFAST = :ultrafast

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # The truncation strategy to use for the model response.
        #
        # - `auto`: If the input to this Response exceeds the model's context window size,
        #   the model will truncate the response to fit the context window by dropping
        #   items from the beginning of the conversation.
        # - `disabled` (default): If the input size will exceed the context window size
        #   for a model, the request will fail with a 400 error.
        #
        # @see OpenAI::Models::Responses::Response#truncation
        module Truncation
          extend OpenAI::Internal::Type::Enum

          AUTO = :auto
          DISABLED = :disabled

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
