module OpenAI
  module Auth
    module TokenType
      JWT: :jwt
      ID: :id
    end

    module SubjectTokenProvider
      def token_type: -> Symbol
      def get_token: -> String
    end

    class WorkloadIdentity
      attr_reader client_id: String?
      attr_reader identity_provider_id: String
      attr_reader service_account_id: String
      attr_reader provider: OpenAI::Auth::SubjectTokenProvider
      attr_reader refresh_buffer_seconds: Integer

      def initialize: (
        provider: OpenAI::Auth::SubjectTokenProvider,
        ?identity_provider_id: (String | Symbol)?,
        ?service_account_id: (String | Symbol)?,
        ?client_id: (String | Symbol)?,
        ?refresh_buffer_seconds: Integer
      ) -> void
    end
  end
end
