module OpenAI
  module Models
    module Realtime
      class UnknownServerEvent
        attr_reader type: Symbol
        attr_reader data: ::Hash[Symbol, untyped]

        def initialize: (data: ::Hash[Symbol, untyped]) -> void
        def to_h: -> ::Hash[Symbol, untyped]
      end
    end
  end
end
