module OpenAI
  module Internal
    class Poller
      DEFAULT_INTERVAL: Float
      DEFAULT_TIMEOUT: Float

      def initialize: (
        operation: String,
        ?poll_interval: (Integer | Float)?,
        ?timeout: (Integer | Float)?
      ) -> void

      def self.validate!: (
        ?poll_interval: (Integer | Float)?,
        ?timeout: (Integer | Float)?
      ) -> [(Float)?, (Float)?]

      def request_options: (
        OpenAI::request_opts? request_options
      ) -> ::Hash[Symbol, top]

      def wait: (OpenAI::Internal::Type::BaseModel resource) -> void
    end
  end
end
