module OpenAI
  module Internal
    class VectorStoreFileUploader
      MAX_FILES_PER_BATCH: Integer

      def initialize: (
        client: OpenAI::Client,
        max_concurrency: Integer,
        request_options: OpenAI::request_opts?
      ) -> void

      def upload: (
        Enumerable[OpenAI::Internal::file_input] files,
        ?max_files: Integer
      ) -> Array[OpenAI::Models::FileObject]
    end
  end
end
