# frozen_string_literal: true

module OpenAI
  module Models
    module Realtime
      class RealtimeConversationItemUserMessage < OpenAI::Internal::Type::BaseModel
        # @!attribute content
        #   The content of the message.
        #
        #   @return [Array<OpenAI::Models::Realtime::RealtimeConversationItemUserMessage::Content>]
        required(
          :content,
          -> { OpenAI::Internal::Type::ArrayOf[OpenAI::Realtime::RealtimeConversationItemUserMessage::Content] }
        )

        # @!attribute role
        #   The role of the message sender. Always `user`.
        #
        #   @return [Symbol, :user]
        required :role, const: :user

        # @!attribute type
        #   The type of the item. Always `message`.
        #
        #   @return [Symbol, :message]
        required :type, const: :message

        # @!attribute id
        #   The unique ID of the item. This may be provided by the client or generated by
        #   the server.
        #
        #   @return [String, nil]
        optional :id, String

        # @!attribute object
        #   Identifier for the API object being returned - always `realtime.item`. Optional
        #   when creating a new item.
        #
        #   @return [Symbol, OpenAI::Models::Realtime::RealtimeConversationItemUserMessage::Object, nil]
        optional :object, enum: -> { OpenAI::Realtime::RealtimeConversationItemUserMessage::Object }

        # @!attribute status
        #   The status of the item. Has no effect on the conversation.
        #
        #   @return [Symbol, OpenAI::Models::Realtime::RealtimeConversationItemUserMessage::Status, nil]
        optional :status, enum: -> { OpenAI::Realtime::RealtimeConversationItemUserMessage::Status }

        # @!method initialize(content:, id: nil, object: nil, status: nil, role: :user, type: :message)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Realtime::RealtimeConversationItemUserMessage} for more
        #   details.
        #
        #   A user message item in a Realtime conversation.
        #
        #   @param content [Array<OpenAI::Models::Realtime::RealtimeConversationItemUserMessage::Content>] The content of the message.
        #
        #   @param id [String] The unique ID of the item. This may be provided by the client or generated by th
        #
        #   @param object [Symbol, OpenAI::Models::Realtime::RealtimeConversationItemUserMessage::Object] Identifier for the API object being returned - always `realtime.item`. Optional
        #
        #   @param status [Symbol, OpenAI::Models::Realtime::RealtimeConversationItemUserMessage::Status] The status of the item. Has no effect on the conversation.
        #
        #   @param role [Symbol, :user] The role of the message sender. Always `user`.
        #
        #   @param type [Symbol, :message] The type of the item. Always `message`.

        class Content < OpenAI::Internal::Type::BaseModel
          # @!attribute audio
          #   Base64-encoded audio bytes (for `input_audio`), these will be parsed as the
          #   format specified in the session input audio type configuration. This defaults to
          #   PCM 16-bit 24kHz mono if not specified.
          #
          #   @return [String, nil]
          optional :audio, String

          # @!attribute detail
          #   The detail level of the image (for `input_image`). `auto` will default to
          #   `high`.
          #
          #   @return [Symbol, OpenAI::Models::Realtime::RealtimeConversationItemUserMessage::Content::Detail, nil]
          optional :detail, enum: -> { OpenAI::Realtime::RealtimeConversationItemUserMessage::Content::Detail }

          # @!attribute image_url
          #   Base64-encoded image bytes (for `input_image`) as a data URI. For example
          #   `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...`. Supported formats are PNG
          #   and JPEG.
          #
          #   @return [String, nil]
          optional :image_url, String

          # @!attribute text
          #   The text content (for `input_text`).
          #
          #   @return [String, nil]
          optional :text, String

          # @!attribute transcript
          #   Transcript of the audio (for `input_audio`). This is not sent to the model, but
          #   will be attached to the message item for reference.
          #
          #   @return [String, nil]
          optional :transcript, String

          # @!attribute type
          #   The content type (`input_text`, `input_audio`, or `input_image`).
          #
          #   @return [Symbol, OpenAI::Models::Realtime::RealtimeConversationItemUserMessage::Content::Type, nil]
          optional :type, enum: -> { OpenAI::Realtime::RealtimeConversationItemUserMessage::Content::Type }

          # @!method initialize(audio: nil, detail: nil, image_url: nil, text: nil, transcript: nil, type: nil)
          #   Some parameter documentations has been truncated, see
          #   {OpenAI::Models::Realtime::RealtimeConversationItemUserMessage::Content} for
          #   more details.
          #
          #   @param audio [String] Base64-encoded audio bytes (for `input_audio`), these will be parsed as the form
          #
          #   @param detail [Symbol, OpenAI::Models::Realtime::RealtimeConversationItemUserMessage::Content::Detail] The detail level of the image (for `input_image`). `auto` will default to `high`
          #
          #   @param image_url [String] Base64-encoded image bytes (for `input_image`) as a data URI. For example `data:
          #
          #   @param text [String] The text content (for `input_text`).
          #
          #   @param transcript [String] Transcript of the audio (for `input_audio`). This is not sent to the model, but
          #
          #   @param type [Symbol, OpenAI::Models::Realtime::RealtimeConversationItemUserMessage::Content::Type] The content type (`input_text`, `input_audio`, or `input_image`).

          # The detail level of the image (for `input_image`). `auto` will default to
          # `high`.
          #
          # @see OpenAI::Models::Realtime::RealtimeConversationItemUserMessage::Content#detail
          module Detail
            extend OpenAI::Internal::Type::Enum

            AUTO = :auto
            LOW = :low
            HIGH = :high

            # @!method self.values
            #   @return [Array<Symbol>]
          end

          # The content type (`input_text`, `input_audio`, or `input_image`).
          #
          # @see OpenAI::Models::Realtime::RealtimeConversationItemUserMessage::Content#type
          module Type
            extend OpenAI::Internal::Type::Enum

            INPUT_TEXT = :input_text
            INPUT_AUDIO = :input_audio
            INPUT_IMAGE = :input_image

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        # Identifier for the API object being returned - always `realtime.item`. Optional
        # when creating a new item.
        #
        # @see OpenAI::Models::Realtime::RealtimeConversationItemUserMessage#object
        module Object
          extend OpenAI::Internal::Type::Enum

          REALTIME_ITEM = :"realtime.item"

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # The status of the item. Has no effect on the conversation.
        #
        # @see OpenAI::Models::Realtime::RealtimeConversationItemUserMessage#status
        module Status
          extend OpenAI::Internal::Type::Enum

          COMPLETED = :completed
          INCOMPLETE = :incomplete
          IN_PROGRESS = :in_progress

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
