module OpenAI
  module Resources
    class Realtime
      class Translations
        attr_reader client_secrets: OpenAI::Resources::Realtime::Translations::ClientSecrets
        def connect: (
          model: String,
          ?request_options: OpenAI::request_opts?,
          ?transport: untyped?,
          ?transport_options: ::Hash[Symbol, untyped]
        ) {
          (OpenAI::Realtime::TranslationConnection connection) -> top
        } -> top

        def initialize: (client: OpenAI::Client) -> void
      end
    end
  end
end
