module OpenAI
  module Resources
    class VectorStores
      class Files
        def create: (
          String vector_store_id,
          file_id: String,
          ?attributes: ::Hash[Symbol, OpenAI::Models::VectorStores::FileCreateParams::attribute]?,
          ?chunking_strategy: OpenAI::Models::file_chunking_strategy_param,
          ?request_options: OpenAI::request_opts
        ) -> OpenAI::VectorStores::VectorStoreFile

        def create_and_poll: (
          String vector_store_id,
          file_id: String,
          ?attributes: ::Hash[Symbol, OpenAI::Models::VectorStores::FileCreateParams::attribute]?,
          ?chunking_strategy: OpenAI::Models::file_chunking_strategy_param,
          ?poll_interval: (Integer | Float)?,
          ?timeout: (Integer | Float)?,
          ?request_options: OpenAI::request_opts
        ) -> OpenAI::VectorStores::VectorStoreFile

        def retrieve: (
          String file_id,
          vector_store_id: String,
          ?request_options: OpenAI::request_opts
        ) -> OpenAI::VectorStores::VectorStoreFile

        def update: (
          String file_id,
          vector_store_id: String,
          attributes: ::Hash[Symbol, OpenAI::Models::VectorStores::FileUpdateParams::attribute]?,
          ?request_options: OpenAI::request_opts
        ) -> OpenAI::VectorStores::VectorStoreFile

        def list: (
          String vector_store_id,
          ?after: String,
          ?before: String,
          ?filter: OpenAI::Models::VectorStores::FileListParams::filter,
          ?limit: Integer,
          ?order: OpenAI::Models::VectorStores::FileListParams::order,
          ?request_options: OpenAI::request_opts
        ) -> OpenAI::Internal::CursorPage[OpenAI::VectorStores::VectorStoreFile]

        def delete: (
          String file_id,
          vector_store_id: String,
          ?request_options: OpenAI::request_opts
        ) -> OpenAI::VectorStores::VectorStoreFileDeleted

        def poll: (
          String file_id,
          vector_store_id: String,
          ?poll_interval: (Integer | Float)?,
          ?timeout: (Integer | Float)?,
          ?request_options: OpenAI::request_opts
        ) -> OpenAI::VectorStores::VectorStoreFile

        def upload: (
          String vector_store_id,
          file: OpenAI::Internal::file_input,
          ?attributes: ::Hash[Symbol, OpenAI::Models::VectorStores::FileCreateParams::attribute]?,
          ?chunking_strategy: OpenAI::Models::file_chunking_strategy_param,
          ?request_options: OpenAI::request_opts
        ) -> OpenAI::VectorStores::VectorStoreFile

        def upload_and_poll: (
          String vector_store_id,
          file: OpenAI::Internal::file_input,
          ?attributes: ::Hash[Symbol, OpenAI::Models::VectorStores::FileCreateParams::attribute]?,
          ?chunking_strategy: OpenAI::Models::file_chunking_strategy_param,
          ?poll_interval: (Integer | Float)?,
          ?timeout: (Integer | Float)?,
          ?request_options: OpenAI::request_opts
        ) -> OpenAI::VectorStores::VectorStoreFile

        def content: (
          String file_id,
          vector_store_id: String,
          ?request_options: OpenAI::request_opts
        ) -> OpenAI::Internal::Page[OpenAI::Models::VectorStores::FileContentResponse]

        def initialize: (client: OpenAI::Client) -> void
      end
    end
  end
end
