# frozen_string_literal: true

module OpenAI
  module Models
    module Beta
      class BetaResponseApplyPatchToolCall < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the apply patch tool call. Populated when this item is returned
        #   via API.
        #
        #   @return [String]
        required :id, String

        # @!attribute call_id
        #   The unique ID of the apply patch tool call generated by the model.
        #
        #   @return [String]
        required :call_id, String

        # @!attribute operation
        #   One of the create_file, delete_file, or update_file operations applied via
        #   apply_patch.
        #
        #   @return [OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Operation::CreateFile, OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Operation::DeleteFile, OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Operation::UpdateFile]
        required :operation, union: -> { OpenAI::Beta::BetaResponseApplyPatchToolCall::Operation }

        # @!attribute status
        #   The status of the apply patch tool call. One of `in_progress` or `completed`.
        #
        #   @return [Symbol, OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Status]
        required :status, enum: -> { OpenAI::Beta::BetaResponseApplyPatchToolCall::Status }

        # @!attribute type
        #   The type of the item. Always `apply_patch_call`.
        #
        #   @return [Symbol, :apply_patch_call]
        required :type, const: :apply_patch_call

        # @!attribute agent
        #   The agent that produced this item.
        #
        #   @return [OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Agent, nil]
        optional :agent, -> { OpenAI::Beta::BetaResponseApplyPatchToolCall::Agent }

        # @!attribute caller_
        #   The execution context that produced this tool call.
        #
        #   @return [OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Caller::Direct, OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Caller::Program, nil]
        optional(
          :caller_,
          union: -> { OpenAI::Beta::BetaResponseApplyPatchToolCall::Caller },
          api_name: :caller,
          nil?: true
        )

        # @!attribute created_by
        #   The ID of the entity that created this tool call.
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!method initialize(id:, call_id:, operation:, status:, agent: nil, caller_: nil, created_by: nil, type: :apply_patch_call)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Beta::BetaResponseApplyPatchToolCall} for more details.
        #
        #   A tool call that applies file diffs by creating, deleting, or updating files.
        #
        #   @param id [String] The unique ID of the apply patch tool call. Populated when this item is returned
        #
        #   @param call_id [String] The unique ID of the apply patch tool call generated by the model.
        #
        #   @param operation [OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Operation::CreateFile, OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Operation::DeleteFile, OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Operation::UpdateFile] One of the create_file, delete_file, or update_file operations applied via apply
        #
        #   @param status [Symbol, OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Status] The status of the apply patch tool call. One of `in_progress` or `completed`.
        #
        #   @param agent [OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Agent] The agent that produced this item.
        #
        #   @param caller_ [OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Caller::Direct, OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Caller::Program, nil] The execution context that produced this tool call.
        #
        #   @param created_by [String] The ID of the entity that created this tool call.
        #
        #   @param type [Symbol, :apply_patch_call] The type of the item. Always `apply_patch_call`.

        # One of the create_file, delete_file, or update_file operations applied via
        # apply_patch.
        #
        # @see OpenAI::Models::Beta::BetaResponseApplyPatchToolCall#operation
        module Operation
          extend OpenAI::Internal::Type::Union

          discriminator :type

          # Instruction describing how to create a file via the apply_patch tool.
          variant :create_file, -> { OpenAI::Beta::BetaResponseApplyPatchToolCall::Operation::CreateFile }

          # Instruction describing how to delete a file via the apply_patch tool.
          variant :delete_file, -> { OpenAI::Beta::BetaResponseApplyPatchToolCall::Operation::DeleteFile }

          # Instruction describing how to update a file via the apply_patch tool.
          variant :update_file, -> { OpenAI::Beta::BetaResponseApplyPatchToolCall::Operation::UpdateFile }

          class CreateFile < OpenAI::Internal::Type::BaseModel
            # @!attribute diff
            #   Diff to apply.
            #
            #   @return [String]
            required :diff, String

            # @!attribute path
            #   Path of the file to create.
            #
            #   @return [String]
            required :path, String

            # @!attribute type
            #   Create a new file with the provided diff.
            #
            #   @return [Symbol, :create_file]
            required :type, const: :create_file

            # @!method initialize(diff:, path:, type: :create_file)
            #   Instruction describing how to create a file via the apply_patch tool.
            #
            #   @param diff [String] Diff to apply.
            #
            #   @param path [String] Path of the file to create.
            #
            #   @param type [Symbol, :create_file] Create a new file with the provided diff.
          end

          class DeleteFile < OpenAI::Internal::Type::BaseModel
            # @!attribute path
            #   Path of the file to delete.
            #
            #   @return [String]
            required :path, String

            # @!attribute type
            #   Delete the specified file.
            #
            #   @return [Symbol, :delete_file]
            required :type, const: :delete_file

            # @!method initialize(path:, type: :delete_file)
            #   Instruction describing how to delete a file via the apply_patch tool.
            #
            #   @param path [String] Path of the file to delete.
            #
            #   @param type [Symbol, :delete_file] Delete the specified file.
          end

          class UpdateFile < OpenAI::Internal::Type::BaseModel
            # @!attribute diff
            #   Diff to apply.
            #
            #   @return [String]
            required :diff, String

            # @!attribute path
            #   Path of the file to update.
            #
            #   @return [String]
            required :path, String

            # @!attribute type
            #   Update an existing file with the provided diff.
            #
            #   @return [Symbol, :update_file]
            required :type, const: :update_file

            # @!method initialize(diff:, path:, type: :update_file)
            #   Instruction describing how to update a file via the apply_patch tool.
            #
            #   @param diff [String] Diff to apply.
            #
            #   @param path [String] Path of the file to update.
            #
            #   @param type [Symbol, :update_file] Update an existing file with the provided diff.
          end

          # @!method self.variants
          #   @return [Array(OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Operation::CreateFile, OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Operation::DeleteFile, OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Operation::UpdateFile)]
        end

        # The status of the apply patch tool call. One of `in_progress` or `completed`.
        #
        # @see OpenAI::Models::Beta::BetaResponseApplyPatchToolCall#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # @see OpenAI::Models::Beta::BetaResponseApplyPatchToolCall#agent
        class Agent < OpenAI::Internal::Type::BaseModel
          # @!attribute agent_name
          #   The canonical name of the agent that produced this item.
          #
          #   @return [String]
          required :agent_name, String

          # @!method initialize(agent_name:)
          #   The agent that produced this item.
          #
          #   @param agent_name [String] The canonical name of the agent that produced this item.
        end

        # The execution context that produced this tool call.
        #
        # @see OpenAI::Models::Beta::BetaResponseApplyPatchToolCall#caller_
        module Caller
          extend OpenAI::Internal::Type::Union

          discriminator :type

          variant :direct, -> { OpenAI::Beta::BetaResponseApplyPatchToolCall::Caller::Direct }

          variant :program, -> { OpenAI::Beta::BetaResponseApplyPatchToolCall::Caller::Program }

          class Direct < OpenAI::Internal::Type::BaseModel
            # @!attribute type
            #
            #   @return [Symbol, :direct]
            required :type, const: :direct

            # @!method initialize(type: :direct)
            #   @param type [Symbol, :direct]
          end

          class Program < OpenAI::Internal::Type::BaseModel
            # @!attribute caller_id
            #   The call ID of the program item that produced this tool call.
            #
            #   @return [String]
            required :caller_id, String

            # @!attribute type
            #
            #   @return [Symbol, :program]
            required :type, const: :program

            # @!method initialize(caller_id:, type: :program)
            #   @param caller_id [String] The call ID of the program item that produced this tool call.
            #
            #   @param type [Symbol, :program]
          end

          # @!method self.variants
          #   @return [Array(OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Caller::Direct, OpenAI::Models::Beta::BetaResponseApplyPatchToolCall::Caller::Program)]
        end
      end
    end

    BetaResponseApplyPatchToolCall = Beta::BetaResponseApplyPatchToolCall
  end
end
