# frozen_string_literal: true

module OpenAI
  module Models
    module Beta
      class BetaResponseFunctionToolCallOutputItem < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the function call tool output.
        #
        #   @return [String]
        required :id, String

        # @!attribute call_id
        #   The unique ID of the function tool call generated by the model.
        #
        #   @return [String]
        required :call_id, String

        # @!attribute output
        #   The output from the function call generated by your code. Can be a string or an
        #   list of output content.
        #
        #   @return [String, Array<OpenAI::Models::Beta::BetaResponseInputText, OpenAI::Models::Beta::BetaResponseInputImage, OpenAI::Models::Beta::BetaResponseInputFile>]
        required :output, union: -> { OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output }

        # @!attribute status
        #   The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        #   Populated when items are returned via API.
        #
        #   @return [Symbol, OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem::Status]
        required :status, enum: -> { OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status }

        # @!attribute type
        #   The type of the function tool call output. Always `function_call_output`.
        #
        #   @return [Symbol, :function_call_output]
        required :type, const: :function_call_output

        # @!attribute agent
        #   The agent that produced this item.
        #
        #   @return [OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem::Agent, nil]
        optional :agent, -> { OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Agent }, nil?: true

        # @!attribute caller_
        #   The execution context that produced this tool call.
        #
        #   @return [OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Direct, OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Program, nil]
        optional(
          :caller_,
          union: -> { OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller },
          api_name: :caller,
          nil?: true
        )

        # @!attribute created_by
        #   The identifier of the actor that created the item.
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!attribute name
        #   The name of the tool that produced the output.
        #
        #   @return [String, nil]
        optional :name, String

        # @!attribute namespace
        #   The namespace of the tool that produced the output.
        #
        #   @return [String, nil]
        optional :namespace, String

        # @!method initialize(id:, call_id:, output:, status:, agent: nil, caller_: nil, created_by: nil, name: nil, namespace: nil, type: :function_call_output)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem} for more details.
        #
        #   @param id [String] The unique ID of the function call tool output.
        #
        #   @param call_id [String] The unique ID of the function tool call generated by the model.
        #
        #   @param output [String, Array<OpenAI::Models::Beta::BetaResponseInputText, OpenAI::Models::Beta::BetaResponseInputImage, OpenAI::Models::Beta::BetaResponseInputFile>] The output from the function call generated by your code.
        #
        #   @param status [Symbol, OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem::Status] The status of the item. One of `in_progress`, `completed`, or
        #
        #   @param agent [OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem::Agent, nil] The agent that produced this item.
        #
        #   @param caller_ [OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Direct, OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Program, nil] The execution context that produced this tool call.
        #
        #   @param created_by [String] The identifier of the actor that created the item.
        #
        #   @param name [String] The name of the tool that produced the output.
        #
        #   @param namespace [String] The namespace of the tool that produced the output.
        #
        #   @param type [Symbol, :function_call_output] The type of the function tool call output. Always `function_call_output`.

        # The output from the function call generated by your code. Can be a string or an
        # list of output content.
        #
        # @see OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem#output
        module Output
          extend OpenAI::Internal::Type::Union

          # A string of the output of the function call.
          variant String

          # Text, image, or file output of the function call.
          variant -> { OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem::Output::OutputContentListArray }

          # A text input to the model.
          module OutputContentList
            extend OpenAI::Internal::Type::Union

            discriminator :type

            # A text input to the model.
            variant :input_text, -> { OpenAI::Beta::BetaResponseInputText }

            # An image input to the model. Learn about [image inputs](https://platform.openai.com/docs/guides/vision).
            variant :input_image, -> { OpenAI::Beta::BetaResponseInputImage }

            # A file input to the model.
            variant :input_file, -> { OpenAI::Beta::BetaResponseInputFile }

            # @!method self.variants
            #   @return [Array(OpenAI::Models::Beta::BetaResponseInputText, OpenAI::Models::Beta::BetaResponseInputImage, OpenAI::Models::Beta::BetaResponseInputFile)]
          end

          # @!method self.variants
          #   @return [Array(String, Array<OpenAI::Models::Beta::BetaResponseInputText, OpenAI::Models::Beta::BetaResponseInputImage, OpenAI::Models::Beta::BetaResponseInputFile>)]

          # @type [OpenAI::Internal::Type::Converter]
          OutputContentListArray = OpenAI::Internal::Type::ArrayOf[
            union: -> {
              OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output::OutputContentList
            }
          ]
        end

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        #
        # @see OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # @see OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem#agent
        class Agent < OpenAI::Internal::Type::BaseModel
          # @!attribute agent_name
          #   The canonical name of the agent that produced this item.
          #
          #   @return [String]
          required :agent_name, String

          # @!method initialize(agent_name:)
          #   The agent that produced this item.
          #
          #   @param agent_name [String] The canonical name of the agent that produced this item.
        end

        # The execution context that produced this tool call.
        #
        # @see OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem#caller_
        module Caller
          extend OpenAI::Internal::Type::Union

          discriminator :type

          variant :direct, -> { OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Direct }

          variant :program, -> { OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Program }

          class Direct < OpenAI::Internal::Type::BaseModel
            # @!attribute type
            #   The caller type. Always `direct`.
            #
            #   @return [Symbol, :direct]
            required :type, const: :direct

            # @!method initialize(type: :direct)
            #   @param type [Symbol, :direct] The caller type. Always `direct`.
          end

          class Program < OpenAI::Internal::Type::BaseModel
            # @!attribute caller_id
            #   The call ID of the program item that produced this tool call.
            #
            #   @return [String]
            required :caller_id, String

            # @!attribute type
            #   The caller type. Always `program`.
            #
            #   @return [Symbol, :program]
            required :type, const: :program

            # @!method initialize(caller_id:, type: :program)
            #   @param caller_id [String] The call ID of the program item that produced this tool call.
            #
            #   @param type [Symbol, :program] The caller type. Always `program`.
          end

          # @!method self.variants
          #   @return [Array(OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Direct, OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Program)]
        end
      end
    end

    BetaResponseFunctionToolCallOutputItem = Beta::BetaResponseFunctionToolCallOutputItem
  end
end
