# frozen_string_literal: true

module OpenAI
  module Models
    module Beta
      class BetaResponseCodeInterpreterToolCall < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the code interpreter tool call.
        #
        #   @return [String]
        required :id, String

        # @!attribute code
        #   The code to run, or null if not available.
        #
        #   @return [String, nil]
        required :code, String, nil?: true

        # @!attribute container_id
        #   The ID of the container used to run the code.
        #
        #   @return [String]
        required :container_id, String

        # @!attribute outputs
        #   The outputs generated by the code interpreter, such as logs or images. Can be
        #   null if no outputs are available.
        #
        #   @return [Array<OpenAI::Models::Beta::BetaResponseCodeInterpreterToolCall::Output::Logs, OpenAI::Models::Beta::BetaResponseCodeInterpreterToolCall::Output::Image>, nil]
        required(
          :outputs,
          -> {
            OpenAI::Internal::Type::ArrayOf[union: OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Output]
          },
          nil?: true
        )

        # @!attribute status
        #   The status of the code interpreter tool call. Valid values are `in_progress`,
        #   `completed`, `incomplete`, `interpreting`, and `failed`.
        #
        #   @return [Symbol, OpenAI::Models::Beta::BetaResponseCodeInterpreterToolCall::Status]
        required :status, enum: -> { OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Status }

        # @!attribute type
        #   The type of the code interpreter tool call. Always `code_interpreter_call`.
        #
        #   @return [Symbol, :code_interpreter_call]
        required :type, const: :code_interpreter_call

        # @!attribute agent
        #   The agent that produced this item.
        #
        #   @return [OpenAI::Models::Beta::BetaResponseCodeInterpreterToolCall::Agent, nil]
        optional :agent, -> { OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Agent }, nil?: true

        # @!method initialize(id:, code:, container_id:, outputs:, status:, agent: nil, type: :code_interpreter_call)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Beta::BetaResponseCodeInterpreterToolCall} for more details.
        #
        #   A tool call to run code.
        #
        #   @param id [String] The unique ID of the code interpreter tool call.
        #
        #   @param code [String, nil] The code to run, or null if not available.
        #
        #   @param container_id [String] The ID of the container used to run the code.
        #
        #   @param outputs [Array<OpenAI::Models::Beta::BetaResponseCodeInterpreterToolCall::Output::Logs, OpenAI::Models::Beta::BetaResponseCodeInterpreterToolCall::Output::Image>, nil] The outputs generated by the code interpreter, such as logs or images.
        #
        #   @param status [Symbol, OpenAI::Models::Beta::BetaResponseCodeInterpreterToolCall::Status] The status of the code interpreter tool call. Valid values are `in_progress`, `c
        #
        #   @param agent [OpenAI::Models::Beta::BetaResponseCodeInterpreterToolCall::Agent, nil] The agent that produced this item.
        #
        #   @param type [Symbol, :code_interpreter_call] The type of the code interpreter tool call. Always `code_interpreter_call`.

        # The logs output from the code interpreter.
        module Output
          extend OpenAI::Internal::Type::Union

          discriminator :type

          # The logs output from the code interpreter.
          variant :logs, -> { OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Output::Logs }

          # The image output from the code interpreter.
          variant :image, -> { OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Output::Image }

          class Logs < OpenAI::Internal::Type::BaseModel
            # @!attribute logs
            #   The logs output from the code interpreter.
            #
            #   @return [String]
            required :logs, String

            # @!attribute type
            #   The type of the output. Always `logs`.
            #
            #   @return [Symbol, :logs]
            required :type, const: :logs

            # @!method initialize(logs:, type: :logs)
            #   The logs output from the code interpreter.
            #
            #   @param logs [String] The logs output from the code interpreter.
            #
            #   @param type [Symbol, :logs] The type of the output. Always `logs`.
          end

          class Image < OpenAI::Internal::Type::BaseModel
            # @!attribute type
            #   The type of the output. Always `image`.
            #
            #   @return [Symbol, :image]
            required :type, const: :image

            # @!attribute url
            #   The URL of the image output from the code interpreter.
            #
            #   @return [String]
            required :url, String

            # @!method initialize(url:, type: :image)
            #   The image output from the code interpreter.
            #
            #   @param url [String] The URL of the image output from the code interpreter.
            #
            #   @param type [Symbol, :image] The type of the output. Always `image`.
          end

          # @!method self.variants
          #   @return [Array(OpenAI::Models::Beta::BetaResponseCodeInterpreterToolCall::Output::Logs, OpenAI::Models::Beta::BetaResponseCodeInterpreterToolCall::Output::Image)]
        end

        # The status of the code interpreter tool call. Valid values are `in_progress`,
        # `completed`, `incomplete`, `interpreting`, and `failed`.
        #
        # @see OpenAI::Models::Beta::BetaResponseCodeInterpreterToolCall#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete
          INTERPRETING = :interpreting
          FAILED = :failed

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # @see OpenAI::Models::Beta::BetaResponseCodeInterpreterToolCall#agent
        class Agent < OpenAI::Internal::Type::BaseModel
          # @!attribute agent_name
          #   The canonical name of the agent that produced this item.
          #
          #   @return [String]
          required :agent_name, String

          # @!method initialize(agent_name:)
          #   The agent that produced this item.
          #
          #   @param agent_name [String] The canonical name of the agent that produced this item.
        end
      end
    end

    BetaResponseCodeInterpreterToolCall = Beta::BetaResponseCodeInterpreterToolCall
  end
end
