# frozen_string_literal: true

module OpenAI
  module Models
    module Beta
      class BetaResponseFunctionToolCall < OpenAI::Internal::Type::BaseModel
        # @!attribute arguments
        #   A JSON string of the arguments to pass to the function.
        #
        #   @return [String]
        required :arguments, String

        # @!attribute call_id
        #   The unique ID of the function tool call generated by the model.
        #
        #   @return [String]
        required :call_id, String

        # @!attribute name
        #   The name of the function to run.
        #
        #   @return [String]
        required :name, String

        # @!attribute type
        #   The type of the function tool call. Always `function_call`.
        #
        #   @return [Symbol, :function_call]
        required :type, const: :function_call

        # @!attribute id
        #   The unique ID of the function tool call.
        #
        #   @return [String, nil]
        optional :id, String

        # @!attribute agent
        #   The agent that produced this item.
        #
        #   @return [OpenAI::Models::Beta::BetaResponseFunctionToolCall::Agent, nil]
        optional :agent, -> { OpenAI::Beta::BetaResponseFunctionToolCall::Agent }, nil?: true

        # @!attribute caller_
        #   The execution context that produced this tool call.
        #
        #   @return [OpenAI::Models::Beta::BetaResponseFunctionToolCall::Caller::Direct, OpenAI::Models::Beta::BetaResponseFunctionToolCall::Caller::Program, nil]
        optional(
          :caller_,
          union: -> { OpenAI::Beta::BetaResponseFunctionToolCall::Caller },
          api_name: :caller,
          nil?: true
        )

        # @!attribute namespace
        #   The namespace of the function to run.
        #
        #   @return [String, nil]
        optional :namespace, String

        # @!attribute status
        #   The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        #   Populated when items are returned via API.
        #
        #   @return [Symbol, OpenAI::Models::Beta::BetaResponseFunctionToolCall::Status, nil]
        optional :status, enum: -> { OpenAI::Beta::BetaResponseFunctionToolCall::Status }

        # @!method initialize(arguments:, call_id:, name:, id: nil, agent: nil, caller_: nil, namespace: nil, status: nil, type: :function_call)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Beta::BetaResponseFunctionToolCall} for more details.
        #
        #   A tool call to run a function. See the
        #   [function calling guide](https://platform.openai.com/docs/guides/function-calling)
        #   for more information.
        #
        #   @param arguments [String] A JSON string of the arguments to pass to the function.
        #
        #   @param call_id [String] The unique ID of the function tool call generated by the model.
        #
        #   @param name [String] The name of the function to run.
        #
        #   @param id [String] The unique ID of the function tool call.
        #
        #   @param agent [OpenAI::Models::Beta::BetaResponseFunctionToolCall::Agent, nil] The agent that produced this item.
        #
        #   @param caller_ [OpenAI::Models::Beta::BetaResponseFunctionToolCall::Caller::Direct, OpenAI::Models::Beta::BetaResponseFunctionToolCall::Caller::Program, nil] The execution context that produced this tool call.
        #
        #   @param namespace [String] The namespace of the function to run.
        #
        #   @param status [Symbol, OpenAI::Models::Beta::BetaResponseFunctionToolCall::Status] The status of the item. One of `in_progress`, `completed`, or
        #
        #   @param type [Symbol, :function_call] The type of the function tool call. Always `function_call`.

        # @see OpenAI::Models::Beta::BetaResponseFunctionToolCall#agent
        class Agent < OpenAI::Internal::Type::BaseModel
          # @!attribute agent_name
          #   The canonical name of the agent that produced this item.
          #
          #   @return [String]
          required :agent_name, String

          # @!method initialize(agent_name:)
          #   The agent that produced this item.
          #
          #   @param agent_name [String] The canonical name of the agent that produced this item.
        end

        # The execution context that produced this tool call.
        #
        # @see OpenAI::Models::Beta::BetaResponseFunctionToolCall#caller_
        module Caller
          extend OpenAI::Internal::Type::Union

          discriminator :type

          variant :direct, -> { OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Direct }

          variant :program, -> { OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Program }

          class Direct < OpenAI::Internal::Type::BaseModel
            # @!attribute type
            #
            #   @return [Symbol, :direct]
            required :type, const: :direct

            # @!method initialize(type: :direct)
            #   @param type [Symbol, :direct]
          end

          class Program < OpenAI::Internal::Type::BaseModel
            # @!attribute caller_id
            #   The call ID of the program item that produced this tool call.
            #
            #   @return [String]
            required :caller_id, String

            # @!attribute type
            #
            #   @return [Symbol, :program]
            required :type, const: :program

            # @!method initialize(caller_id:, type: :program)
            #   @param caller_id [String] The call ID of the program item that produced this tool call.
            #
            #   @param type [Symbol, :program]
          end

          # @!method self.variants
          #   @return [Array(OpenAI::Models::Beta::BetaResponseFunctionToolCall::Caller::Direct, OpenAI::Models::Beta::BetaResponseFunctionToolCall::Caller::Program)]
        end

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        #
        # @see OpenAI::Models::Beta::BetaResponseFunctionToolCall#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end

    BetaResponseFunctionToolCall = Beta::BetaResponseFunctionToolCall
  end
end
