# frozen_string_literal: true

module OpenAI
  module Models
    module Beta
      # Content item used to generate a response.
      module BetaResponseItem
        extend OpenAI::Internal::Type::Union

        discriminator :type

        variant :message, -> { OpenAI::Beta::BetaResponseInputMessageItem }

        # An output message from the model.
        variant :message, -> { OpenAI::Beta::BetaResponseOutputMessage }

        # The results of a file search tool call. See the
        # [file search guide](https://platform.openai.com/docs/guides/tools-file-search) for more information.
        variant :file_search_call, -> { OpenAI::Beta::BetaResponseFileSearchToolCall }

        # A tool call to a computer use tool. See the
        # [computer use guide](https://platform.openai.com/docs/guides/tools-computer-use) for more information.
        variant :computer_call, -> { OpenAI::Beta::BetaResponseComputerToolCall }

        variant :computer_call_output, -> { OpenAI::Beta::BetaResponseComputerToolCallOutputItem }

        # The results of a web search tool call. See the
        # [web search guide](https://platform.openai.com/docs/guides/tools-web-search) for more information.
        variant :web_search_call, -> { OpenAI::Beta::BetaResponseFunctionWebSearch }

        # A tool call to run a function. See the
        # [function calling guide](https://platform.openai.com/docs/guides/function-calling) for more information.
        variant :function_call, -> { OpenAI::Beta::BetaResponseFunctionToolCallItem }

        variant :function_call_output, -> { OpenAI::Beta::BetaResponseFunctionToolCallOutputItem }

        variant :agent_message, -> { OpenAI::Beta::BetaResponseItem::AgentMessage }

        variant :multi_agent_call, -> { OpenAI::Beta::BetaResponseItem::MultiAgentCall }

        variant :multi_agent_call_output, -> { OpenAI::Beta::BetaResponseItem::MultiAgentCallOutput }

        variant :tool_search_call, -> { OpenAI::Beta::BetaResponseToolSearchCall }

        variant :tool_search_output, -> { OpenAI::Beta::BetaResponseToolSearchOutputItem }

        variant :additional_tools, -> { OpenAI::Beta::BetaResponseItem::AdditionalTools }

        # A description of the chain of thought used by a reasoning model while generating
        # a response. Be sure to include these items in your `input` to the Responses API
        # for subsequent turns of a conversation if you are manually
        # [managing context](https://platform.openai.com/docs/guides/conversation-state).
        variant :reasoning, -> { OpenAI::Beta::BetaResponseReasoningItem }

        variant :program, -> { OpenAI::Beta::BetaResponseItem::Program }

        variant :program_output, -> { OpenAI::Beta::BetaResponseItem::ProgramOutput }

        # A compaction item generated by the [`v1/responses/compact` API](https://platform.openai.com/docs/api-reference/responses/compact).
        variant :compaction, -> { OpenAI::Beta::BetaResponseCompactionItem }

        # An image generation request made by the model.
        variant :image_generation_call, -> { OpenAI::Beta::BetaResponseItem::ImageGenerationCall }

        # A tool call to run code.
        variant :code_interpreter_call, -> { OpenAI::Beta::BetaResponseCodeInterpreterToolCall }

        # A tool call to run a command on the local shell.
        variant :local_shell_call, -> { OpenAI::Beta::BetaResponseItem::LocalShellCall }

        # The output of a local shell tool call.
        variant :local_shell_call_output, -> { OpenAI::Beta::BetaResponseItem::LocalShellCallOutput }

        # A tool call that executes one or more shell commands in a managed environment.
        variant :shell_call, -> { OpenAI::Beta::BetaResponseFunctionShellToolCall }

        # The output of a shell tool call that was emitted.
        variant :shell_call_output, -> { OpenAI::Beta::BetaResponseFunctionShellToolCallOutput }

        # A tool call that applies file diffs by creating, deleting, or updating files.
        variant :apply_patch_call, -> { OpenAI::Beta::BetaResponseApplyPatchToolCall }

        # The output emitted by an apply patch tool call.
        variant :apply_patch_call_output, -> { OpenAI::Beta::BetaResponseApplyPatchToolCallOutput }

        # A list of tools available on an MCP server.
        variant :mcp_list_tools, -> { OpenAI::Beta::BetaResponseItem::McpListTools }

        # A request for human approval of a tool invocation.
        variant :mcp_approval_request, -> { OpenAI::Beta::BetaResponseItem::McpApprovalRequest }

        # A response to an MCP approval request.
        variant :mcp_approval_response, -> { OpenAI::Beta::BetaResponseItem::McpApprovalResponse }

        # An invocation of a tool on an MCP server.
        variant :mcp_call, -> { OpenAI::Beta::BetaResponseItem::McpCall }

        # A call to a custom tool created by the model.
        variant :custom_tool_call, -> { OpenAI::Beta::BetaResponseCustomToolCallItem }

        # The output of a custom tool call from your code, being sent back to the model.
        variant :custom_tool_call_output, -> { OpenAI::Beta::BetaResponseCustomToolCallOutputItem }

        class AgentMessage < OpenAI::Internal::Type::BaseModel
          # @!attribute id
          #   The unique ID of the agent message.
          #
          #   @return [String]
          required :id, String

          # @!attribute author
          #   The sending agent identity.
          #
          #   @return [String]
          required :author, String

          # @!attribute content
          #   Encrypted content sent between agents.
          #
          #   @return [Array<OpenAI::Models::Beta::BetaResponseInputText, OpenAI::Models::Beta::BetaResponseOutputText, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::Text, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::SummaryText, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::ReasoningText, OpenAI::Models::Beta::BetaResponseOutputRefusal, OpenAI::Models::Beta::BetaResponseInputImage, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::ComputerScreenshot, OpenAI::Models::Beta::BetaResponseInputFile, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::EncryptedContent>]
          required(
            :content,
            -> { OpenAI::Internal::Type::ArrayOf[union: OpenAI::Beta::BetaResponseItem::AgentMessage::Content] }
          )

          # @!attribute recipient
          #   The destination agent identity.
          #
          #   @return [String]
          required :recipient, String

          # @!attribute type
          #   The type of the item. Always `agent_message`.
          #
          #   @return [Symbol, :agent_message]
          required :type, const: :agent_message

          # @!attribute agent
          #   The agent that produced this item.
          #
          #   @return [OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Agent, nil]
          optional :agent, -> { OpenAI::Beta::BetaResponseItem::AgentMessage::Agent }

          # @!method initialize(id:, author:, content:, recipient:, agent: nil, type: :agent_message)
          #   @param id [String] The unique ID of the agent message.
          #
          #   @param author [String] The sending agent identity.
          #
          #   @param content [Array<OpenAI::Models::Beta::BetaResponseInputText, OpenAI::Models::Beta::BetaResponseOutputText, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::Text, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::SummaryText, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::ReasoningText, OpenAI::Models::Beta::BetaResponseOutputRefusal, OpenAI::Models::Beta::BetaResponseInputImage, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::ComputerScreenshot, OpenAI::Models::Beta::BetaResponseInputFile, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::EncryptedContent>] Encrypted content sent between agents.
          #
          #   @param recipient [String] The destination agent identity.
          #
          #   @param agent [OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Agent] The agent that produced this item.
          #
          #   @param type [Symbol, :agent_message] The type of the item. Always `agent_message`.

          # A content part that makes up an input or output item.
          module Content
            extend OpenAI::Internal::Type::Union

            discriminator :type

            # A text input to the model.
            variant :input_text, -> { OpenAI::Beta::BetaResponseInputText }

            # A text output from the model.
            variant :output_text, -> { OpenAI::Beta::BetaResponseOutputText }

            # A text content.
            variant :text, -> { OpenAI::Beta::BetaResponseItem::AgentMessage::Content::Text }

            # A summary text from the model.
            variant :summary_text, -> { OpenAI::Beta::BetaResponseItem::AgentMessage::Content::SummaryText }

            # Reasoning text from the model.
            variant :reasoning_text, -> { OpenAI::Beta::BetaResponseItem::AgentMessage::Content::ReasoningText }

            # A refusal from the model.
            variant :refusal, -> { OpenAI::Beta::BetaResponseOutputRefusal }

            # An image input to the model. Learn about [image inputs](https://platform.openai.com/docs/guides/vision).
            variant :input_image, -> { OpenAI::Beta::BetaResponseInputImage }

            # A screenshot of a computer.
            variant(
              :computer_screenshot,
              -> { OpenAI::Beta::BetaResponseItem::AgentMessage::Content::ComputerScreenshot }
            )

            # A file input to the model.
            variant :input_file, -> { OpenAI::Beta::BetaResponseInputFile }

            # Opaque encrypted content that Responses API decrypts inside trusted model execution.
            variant :encrypted_content, -> { OpenAI::Beta::BetaResponseItem::AgentMessage::Content::EncryptedContent }

            class Text < OpenAI::Internal::Type::BaseModel
              # @!attribute text
              #
              #   @return [String]
              required :text, String

              # @!attribute type
              #
              #   @return [Symbol, :text]
              required :type, const: :text

              # @!method initialize(text:, type: :text)
              #   A text content.
              #
              #   @param text [String]
              #   @param type [Symbol, :text]
            end

            class SummaryText < OpenAI::Internal::Type::BaseModel
              # @!attribute text
              #   A summary of the reasoning output from the model so far.
              #
              #   @return [String]
              required :text, String

              # @!attribute type
              #   The type of the object. Always `summary_text`.
              #
              #   @return [Symbol, :summary_text]
              required :type, const: :summary_text

              # @!method initialize(text:, type: :summary_text)
              #   A summary text from the model.
              #
              #   @param text [String] A summary of the reasoning output from the model so far.
              #
              #   @param type [Symbol, :summary_text] The type of the object. Always `summary_text`.
            end

            class ReasoningText < OpenAI::Internal::Type::BaseModel
              # @!attribute text
              #   The reasoning text from the model.
              #
              #   @return [String]
              required :text, String

              # @!attribute type
              #   The type of the reasoning text. Always `reasoning_text`.
              #
              #   @return [Symbol, :reasoning_text]
              required :type, const: :reasoning_text

              # @!method initialize(text:, type: :reasoning_text)
              #   Reasoning text from the model.
              #
              #   @param text [String] The reasoning text from the model.
              #
              #   @param type [Symbol, :reasoning_text] The type of the reasoning text. Always `reasoning_text`.
            end

            class ComputerScreenshot < OpenAI::Internal::Type::BaseModel
              # @!attribute detail
              #   The detail level of the screenshot image to be sent to the model. One of `high`,
              #   `low`, `auto`, or `original`. Defaults to `auto`.
              #
              #   @return [Symbol, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::ComputerScreenshot::Detail]
              required(
                :detail,
                enum: -> { OpenAI::Beta::BetaResponseItem::AgentMessage::Content::ComputerScreenshot::Detail }
              )

              # @!attribute file_id
              #   The identifier of an uploaded file that contains the screenshot.
              #
              #   @return [String, nil]
              required :file_id, String, nil?: true

              # @!attribute image_url
              #   The URL of the screenshot image.
              #
              #   @return [String, nil]
              required :image_url, String, nil?: true

              # @!attribute type
              #   Specifies the event type. For a computer screenshot, this property is always set
              #   to `computer_screenshot`.
              #
              #   @return [Symbol, :computer_screenshot]
              required :type, const: :computer_screenshot

              # @!attribute prompt_cache_breakpoint
              #   Marks the exact end of a reusable prompt prefix. The breakpoint inherits its TTL
              #   from the request's `prompt_cache_options.ttl`; the boundary is not rounded to a
              #   token block.
              #
              #   @return [OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::ComputerScreenshot::PromptCacheBreakpoint, nil]
              optional(
                :prompt_cache_breakpoint,
                -> { OpenAI::Beta::BetaResponseItem::AgentMessage::Content::ComputerScreenshot::PromptCacheBreakpoint }
              )

              # @!method initialize(detail:, file_id:, image_url:, prompt_cache_breakpoint: nil, type: :computer_screenshot)
              #   Some parameter documentations has been truncated, see
              #   {OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::ComputerScreenshot}
              #   for more details.
              #
              #   A screenshot of a computer.
              #
              #   @param detail [Symbol, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::ComputerScreenshot::Detail] The detail level of the screenshot image to be sent to the model. One of `high`,
              #
              #   @param file_id [String, nil] The identifier of an uploaded file that contains the screenshot.
              #
              #   @param image_url [String, nil] The URL of the screenshot image.
              #
              #   @param prompt_cache_breakpoint [OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::ComputerScreenshot::PromptCacheBreakpoint] Marks the exact end of a reusable prompt prefix. The breakpoint inherits its TTL
              #
              #   @param type [Symbol, :computer_screenshot] Specifies the event type. For a computer screenshot, this property is always set

              # The detail level of the screenshot image to be sent to the model. One of `high`,
              # `low`, `auto`, or `original`. Defaults to `auto`.
              #
              # @see OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::ComputerScreenshot#detail
              module Detail
                extend OpenAI::Internal::Type::Enum

                LOW = :low
                HIGH = :high
                AUTO = :auto
                ORIGINAL = :original

                # @!method self.values
                #   @return [Array<Symbol>]
              end

              # @see OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::ComputerScreenshot#prompt_cache_breakpoint
              class PromptCacheBreakpoint < OpenAI::Internal::Type::BaseModel
                # @!attribute mode
                #   The breakpoint mode. Always `explicit`.
                #
                #   @return [Symbol, :explicit]
                required :mode, const: :explicit

                # @!method initialize(mode: :explicit)
                #   Marks the exact end of a reusable prompt prefix. The breakpoint inherits its TTL
                #   from the request's `prompt_cache_options.ttl`; the boundary is not rounded to a
                #   token block.
                #
                #   @param mode [Symbol, :explicit] The breakpoint mode. Always `explicit`.
              end
            end

            class EncryptedContent < OpenAI::Internal::Type::BaseModel
              # @!attribute encrypted_content
              #   Opaque encrypted content.
              #
              #   @return [String]
              required :encrypted_content, String

              # @!attribute type
              #   The type of the input item. Always `encrypted_content`.
              #
              #   @return [Symbol, :encrypted_content]
              required :type, const: :encrypted_content

              # @!method initialize(encrypted_content:, type: :encrypted_content)
              #   Opaque encrypted content that Responses API decrypts inside trusted model
              #   execution.
              #
              #   @param encrypted_content [String] Opaque encrypted content.
              #
              #   @param type [Symbol, :encrypted_content] The type of the input item. Always `encrypted_content`.
            end

            # @!method self.variants
            #   @return [Array(OpenAI::Models::Beta::BetaResponseInputText, OpenAI::Models::Beta::BetaResponseOutputText, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::Text, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::SummaryText, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::ReasoningText, OpenAI::Models::Beta::BetaResponseOutputRefusal, OpenAI::Models::Beta::BetaResponseInputImage, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::ComputerScreenshot, OpenAI::Models::Beta::BetaResponseInputFile, OpenAI::Models::Beta::BetaResponseItem::AgentMessage::Content::EncryptedContent)]
          end

          # @see OpenAI::Models::Beta::BetaResponseItem::AgentMessage#agent
          class Agent < OpenAI::Internal::Type::BaseModel
            # @!attribute agent_name
            #   The canonical name of the agent that produced this item.
            #
            #   @return [String]
            required :agent_name, String

            # @!method initialize(agent_name:)
            #   The agent that produced this item.
            #
            #   @param agent_name [String] The canonical name of the agent that produced this item.
          end
        end

        class MultiAgentCall < OpenAI::Internal::Type::BaseModel
          # @!attribute id
          #   The unique ID of the multi-agent call item.
          #
          #   @return [String]
          required :id, String

          # @!attribute action
          #   The multi-agent action to execute.
          #
          #   @return [Symbol, OpenAI::Models::Beta::BetaResponseItem::MultiAgentCall::Action]
          required :action, enum: -> { OpenAI::Beta::BetaResponseItem::MultiAgentCall::Action }

          # @!attribute arguments
          #   The JSON string of arguments generated for the action.
          #
          #   @return [String]
          required :arguments, String

          # @!attribute call_id
          #   The unique ID linking this call to its output.
          #
          #   @return [String]
          required :call_id, String

          # @!attribute type
          #   The type of the multi-agent call. Always `multi_agent_call`.
          #
          #   @return [Symbol, :multi_agent_call]
          required :type, const: :multi_agent_call

          # @!attribute agent
          #   The agent that produced this item.
          #
          #   @return [OpenAI::Models::Beta::BetaResponseItem::MultiAgentCall::Agent, nil]
          optional :agent, -> { OpenAI::Beta::BetaResponseItem::MultiAgentCall::Agent }

          # @!method initialize(id:, action:, arguments:, call_id:, agent: nil, type: :multi_agent_call)
          #   @param id [String] The unique ID of the multi-agent call item.
          #
          #   @param action [Symbol, OpenAI::Models::Beta::BetaResponseItem::MultiAgentCall::Action] The multi-agent action to execute.
          #
          #   @param arguments [String] The JSON string of arguments generated for the action.
          #
          #   @param call_id [String] The unique ID linking this call to its output.
          #
          #   @param agent [OpenAI::Models::Beta::BetaResponseItem::MultiAgentCall::Agent] The agent that produced this item.
          #
          #   @param type [Symbol, :multi_agent_call] The type of the multi-agent call. Always `multi_agent_call`.

          # The multi-agent action to execute.
          #
          # @see OpenAI::Models::Beta::BetaResponseItem::MultiAgentCall#action
          module Action
            extend OpenAI::Internal::Type::Enum

            SPAWN_AGENT = :spawn_agent
            INTERRUPT_AGENT = :interrupt_agent
            LIST_AGENTS = :list_agents
            SEND_MESSAGE = :send_message
            FOLLOWUP_TASK = :followup_task
            WAIT_AGENT = :wait_agent

            # @!method self.values
            #   @return [Array<Symbol>]
          end

          # @see OpenAI::Models::Beta::BetaResponseItem::MultiAgentCall#agent
          class Agent < OpenAI::Internal::Type::BaseModel
            # @!attribute agent_name
            #   The canonical name of the agent that produced this item.
            #
            #   @return [String]
            required :agent_name, String

            # @!method initialize(agent_name:)
            #   The agent that produced this item.
            #
            #   @param agent_name [String] The canonical name of the agent that produced this item.
          end
        end

        class MultiAgentCallOutput < OpenAI::Internal::Type::BaseModel
          # @!attribute id
          #   The unique ID of the multi-agent call output item.
          #
          #   @return [String]
          required :id, String

          # @!attribute action
          #   The multi-agent action that produced this result.
          #
          #   @return [Symbol, OpenAI::Models::Beta::BetaResponseItem::MultiAgentCallOutput::Action]
          required :action, enum: -> { OpenAI::Beta::BetaResponseItem::MultiAgentCallOutput::Action }

          # @!attribute call_id
          #   The unique ID of the multi-agent call.
          #
          #   @return [String]
          required :call_id, String

          # @!attribute output
          #   Text output returned by the multi-agent action.
          #
          #   @return [Array<OpenAI::Models::Beta::BetaResponseOutputText>]
          required :output, -> { OpenAI::Internal::Type::ArrayOf[OpenAI::Beta::BetaResponseOutputText] }

          # @!attribute type
          #   The type of the multi-agent result. Always `multi_agent_call_output`.
          #
          #   @return [Symbol, :multi_agent_call_output]
          required :type, const: :multi_agent_call_output

          # @!attribute agent
          #   The agent that produced this item.
          #
          #   @return [OpenAI::Models::Beta::BetaResponseItem::MultiAgentCallOutput::Agent, nil]
          optional :agent, -> { OpenAI::Beta::BetaResponseItem::MultiAgentCallOutput::Agent }

          # @!method initialize(id:, action:, call_id:, output:, agent: nil, type: :multi_agent_call_output)
          #   @param id [String] The unique ID of the multi-agent call output item.
          #
          #   @param action [Symbol, OpenAI::Models::Beta::BetaResponseItem::MultiAgentCallOutput::Action] The multi-agent action that produced this result.
          #
          #   @param call_id [String] The unique ID of the multi-agent call.
          #
          #   @param output [Array<OpenAI::Models::Beta::BetaResponseOutputText>] Text output returned by the multi-agent action.
          #
          #   @param agent [OpenAI::Models::Beta::BetaResponseItem::MultiAgentCallOutput::Agent] The agent that produced this item.
          #
          #   @param type [Symbol, :multi_agent_call_output] The type of the multi-agent result. Always `multi_agent_call_output`.

          # The multi-agent action that produced this result.
          #
          # @see OpenAI::Models::Beta::BetaResponseItem::MultiAgentCallOutput#action
          module Action
            extend OpenAI::Internal::Type::Enum

            SPAWN_AGENT = :spawn_agent
            INTERRUPT_AGENT = :interrupt_agent
            LIST_AGENTS = :list_agents
            SEND_MESSAGE = :send_message
            FOLLOWUP_TASK = :followup_task
            WAIT_AGENT = :wait_agent

            # @!method self.values
            #   @return [Array<Symbol>]
          end

          # @see OpenAI::Models::Beta::BetaResponseItem::MultiAgentCallOutput#agent
          class Agent < OpenAI::Internal::Type::BaseModel
            # @!attribute agent_name
            #   The canonical name of the agent that produced this item.
            #
            #   @return [String]
            required :agent_name, String

            # @!method initialize(agent_name:)
            #   The agent that produced this item.
            #
            #   @param agent_name [String] The canonical name of the agent that produced this item.
          end
        end

        class AdditionalTools < OpenAI::Internal::Type::BaseModel
          # @!attribute id
          #   The unique ID of the additional tools item.
          #
          #   @return [String]
          required :id, String

          # @!attribute role
          #   The role that provided the additional tools.
          #
          #   @return [Symbol, OpenAI::Models::Beta::BetaResponseItem::AdditionalTools::Role]
          required :role, enum: -> { OpenAI::Beta::BetaResponseItem::AdditionalTools::Role }

          # @!attribute tools
          #   The additional tool definitions made available at this item.
          #
          #   @return [Array<OpenAI::Models::Beta::BetaFunctionTool, OpenAI::Models::Beta::BetaFileSearchTool, OpenAI::Models::Beta::BetaComputerTool, OpenAI::Models::Beta::BetaComputerUsePreviewTool, OpenAI::Models::Beta::BetaTool::Mcp, OpenAI::Models::Beta::BetaTool::CodeInterpreter, OpenAI::Models::Beta::BetaTool::ProgrammaticToolCalling, OpenAI::Models::Beta::BetaTool::ImageGeneration, OpenAI::Models::Beta::BetaTool::LocalShell, OpenAI::Models::Beta::BetaFunctionShellTool, OpenAI::Models::Beta::BetaCustomTool, OpenAI::Models::Beta::BetaNamespaceTool, OpenAI::Models::Beta::BetaToolSearchTool, OpenAI::Models::Beta::BetaApplyPatchTool, OpenAI::Models::Beta::BetaWebSearchTool, OpenAI::Models::Beta::BetaWebSearchPreviewTool>]
          required :tools, -> { OpenAI::Internal::Type::ArrayOf[union: OpenAI::Beta::BetaTool] }

          # @!attribute type
          #   The type of the item. Always `additional_tools`.
          #
          #   @return [Symbol, :additional_tools]
          required :type, const: :additional_tools

          # @!attribute agent
          #   The agent that produced this item.
          #
          #   @return [OpenAI::Models::Beta::BetaResponseItem::AdditionalTools::Agent, nil]
          optional :agent, -> { OpenAI::Beta::BetaResponseItem::AdditionalTools::Agent }

          # @!method initialize(id:, role:, tools:, agent: nil, type: :additional_tools)
          #   @param id [String] The unique ID of the additional tools item.
          #
          #   @param role [Symbol, OpenAI::Models::Beta::BetaResponseItem::AdditionalTools::Role] The role that provided the additional tools.
          #
          #   @param tools [Array<OpenAI::Models::Beta::BetaFunctionTool, OpenAI::Models::Beta::BetaFileSearchTool, OpenAI::Models::Beta::BetaComputerTool, OpenAI::Models::Beta::BetaComputerUsePreviewTool, OpenAI::Models::Beta::BetaTool::Mcp, OpenAI::Models::Beta::BetaTool::CodeInterpreter, OpenAI::Models::Beta::BetaTool::ProgrammaticToolCalling, OpenAI::Models::Beta::BetaTool::ImageGeneration, OpenAI::Models::Beta::BetaTool::LocalShell, OpenAI::Models::Beta::BetaFunctionShellTool, OpenAI::Models::Beta::BetaCustomTool, OpenAI::Models::Beta::BetaNamespaceTool, OpenAI::Models::Beta::BetaToolSearchTool, OpenAI::Models::Beta::BetaApplyPatchTool, OpenAI::Models::Beta::BetaWebSearchTool, OpenAI::Models::Beta::BetaWebSearchPreviewTool>] The additional tool definitions made available at this item.
          #
          #   @param agent [OpenAI::Models::Beta::BetaResponseItem::AdditionalTools::Agent] The agent that produced this item.
          #
          #   @param type [Symbol, :additional_tools] The type of the item. Always `additional_tools`.

          # The role that provided the additional tools.
          #
          # @see OpenAI::Models::Beta::BetaResponseItem::AdditionalTools#role
          module Role
            extend OpenAI::Internal::Type::Enum

            UNKNOWN = :unknown
            USER = :user
            ASSISTANT = :assistant
            SYSTEM = :system
            CRITIC = :critic
            DISCRIMINATOR = :discriminator
            DEVELOPER = :developer
            TOOL = :tool

            # @!method self.values
            #   @return [Array<Symbol>]
          end

          # @see OpenAI::Models::Beta::BetaResponseItem::AdditionalTools#agent
          class Agent < OpenAI::Internal::Type::BaseModel
            # @!attribute agent_name
            #   The canonical name of the agent that produced this item.
            #
            #   @return [String]
            required :agent_name, String

            # @!method initialize(agent_name:)
            #   The agent that produced this item.
            #
            #   @param agent_name [String] The canonical name of the agent that produced this item.
          end
        end

        class Program < OpenAI::Internal::Type::BaseModel
          # @!attribute id
          #   The unique ID of the program item.
          #
          #   @return [String]
          required :id, String

          # @!attribute call_id
          #   The stable call ID of the program item.
          #
          #   @return [String]
          required :call_id, String

          # @!attribute code
          #   The JavaScript source executed by programmatic tool calling.
          #
          #   @return [String]
          required :code, String

          # @!attribute fingerprint
          #   Opaque program replay fingerprint that must be round-tripped.
          #
          #   @return [String]
          required :fingerprint, String

          # @!attribute type
          #   The type of the item. Always `program`.
          #
          #   @return [Symbol, :program]
          required :type, const: :program

          # @!attribute agent
          #   The agent that produced this item.
          #
          #   @return [OpenAI::Models::Beta::BetaResponseItem::Program::Agent, nil]
          optional :agent, -> { OpenAI::Beta::BetaResponseItem::Program::Agent }

          # @!method initialize(id:, call_id:, code:, fingerprint:, agent: nil, type: :program)
          #   @param id [String] The unique ID of the program item.
          #
          #   @param call_id [String] The stable call ID of the program item.
          #
          #   @param code [String] The JavaScript source executed by programmatic tool calling.
          #
          #   @param fingerprint [String] Opaque program replay fingerprint that must be round-tripped.
          #
          #   @param agent [OpenAI::Models::Beta::BetaResponseItem::Program::Agent] The agent that produced this item.
          #
          #   @param type [Symbol, :program] The type of the item. Always `program`.

          # @see OpenAI::Models::Beta::BetaResponseItem::Program#agent
          class Agent < OpenAI::Internal::Type::BaseModel
            # @!attribute agent_name
            #   The canonical name of the agent that produced this item.
            #
            #   @return [String]
            required :agent_name, String

            # @!method initialize(agent_name:)
            #   The agent that produced this item.
            #
            #   @param agent_name [String] The canonical name of the agent that produced this item.
          end
        end

        class ProgramOutput < OpenAI::Internal::Type::BaseModel
          # @!attribute id
          #   The unique ID of the program output item.
          #
          #   @return [String]
          required :id, String

          # @!attribute call_id
          #   The call ID of the program item.
          #
          #   @return [String]
          required :call_id, String

          # @!attribute result
          #   The result produced by the program item.
          #
          #   @return [String]
          required :result, String

          # @!attribute status
          #   The terminal status of the program output item.
          #
          #   @return [Symbol, OpenAI::Models::Beta::BetaResponseItem::ProgramOutput::Status]
          required :status, enum: -> { OpenAI::Beta::BetaResponseItem::ProgramOutput::Status }

          # @!attribute type
          #   The type of the item. Always `program_output`.
          #
          #   @return [Symbol, :program_output]
          required :type, const: :program_output

          # @!attribute agent
          #   The agent that produced this item.
          #
          #   @return [OpenAI::Models::Beta::BetaResponseItem::ProgramOutput::Agent, nil]
          optional :agent, -> { OpenAI::Beta::BetaResponseItem::ProgramOutput::Agent }

          # @!method initialize(id:, call_id:, result:, status:, agent: nil, type: :program_output)
          #   @param id [String] The unique ID of the program output item.
          #
          #   @param call_id [String] The call ID of the program item.
          #
          #   @param result [String] The result produced by the program item.
          #
          #   @param status [Symbol, OpenAI::Models::Beta::BetaResponseItem::ProgramOutput::Status] The terminal status of the program output item.
          #
          #   @param agent [OpenAI::Models::Beta::BetaResponseItem::ProgramOutput::Agent] The agent that produced this item.
          #
          #   @param type [Symbol, :program_output] The type of the item. Always `program_output`.

          # The terminal status of the program output item.
          #
          # @see OpenAI::Models::Beta::BetaResponseItem::ProgramOutput#status
          module Status
            extend OpenAI::Internal::Type::Enum

            COMPLETED = :completed
            INCOMPLETE = :incomplete

            # @!method self.values
            #   @return [Array<Symbol>]
          end

          # @see OpenAI::Models::Beta::BetaResponseItem::ProgramOutput#agent
          class Agent < OpenAI::Internal::Type::BaseModel
            # @!attribute agent_name
            #   The canonical name of the agent that produced this item.
            #
            #   @return [String]
            required :agent_name, String

            # @!method initialize(agent_name:)
            #   The agent that produced this item.
            #
            #   @param agent_name [String] The canonical name of the agent that produced this item.
          end
        end

        class ImageGenerationCall < OpenAI::Internal::Type::BaseModel
          # @!attribute id
          #   The unique ID of the image generation call.
          #
          #   @return [String]
          required :id, String

          # @!attribute result
          #   The generated image encoded in base64.
          #
          #   @return [String, nil]
          required :result, String, nil?: true

          # @!attribute status
          #   The status of the image generation call.
          #
          #   @return [Symbol, OpenAI::Models::Beta::BetaResponseItem::ImageGenerationCall::Status]
          required :status, enum: -> { OpenAI::Beta::BetaResponseItem::ImageGenerationCall::Status }

          # @!attribute type
          #   The type of the image generation call. Always `image_generation_call`.
          #
          #   @return [Symbol, :image_generation_call]
          required :type, const: :image_generation_call

          # @!attribute agent
          #   The agent that produced this item.
          #
          #   @return [OpenAI::Models::Beta::BetaResponseItem::ImageGenerationCall::Agent, nil]
          optional :agent, -> { OpenAI::Beta::BetaResponseItem::ImageGenerationCall::Agent }, nil?: true

          # @!method initialize(id:, result:, status:, agent: nil, type: :image_generation_call)
          #   Some parameter documentations has been truncated, see
          #   {OpenAI::Models::Beta::BetaResponseItem::ImageGenerationCall} for more details.
          #
          #   An image generation request made by the model.
          #
          #   @param id [String] The unique ID of the image generation call.
          #
          #   @param result [String, nil] The generated image encoded in base64.
          #
          #   @param status [Symbol, OpenAI::Models::Beta::BetaResponseItem::ImageGenerationCall::Status] The status of the image generation call.
          #
          #   @param agent [OpenAI::Models::Beta::BetaResponseItem::ImageGenerationCall::Agent, nil] The agent that produced this item.
          #
          #   @param type [Symbol, :image_generation_call] The type of the image generation call. Always `image_generation_call`.

          # The status of the image generation call.
          #
          # @see OpenAI::Models::Beta::BetaResponseItem::ImageGenerationCall#status
          module Status
            extend OpenAI::Internal::Type::Enum

            IN_PROGRESS = :in_progress
            COMPLETED = :completed
            GENERATING = :generating
            FAILED = :failed

            # @!method self.values
            #   @return [Array<Symbol>]
          end

          # @see OpenAI::Models::Beta::BetaResponseItem::ImageGenerationCall#agent
          class Agent < OpenAI::Internal::Type::BaseModel
            # @!attribute agent_name
            #   The canonical name of the agent that produced this item.
            #
            #   @return [String]
            required :agent_name, String

            # @!method initialize(agent_name:)
            #   The agent that produced this item.
            #
            #   @param agent_name [String] The canonical name of the agent that produced this item.
          end
        end

        class LocalShellCall < OpenAI::Internal::Type::BaseModel
          # @!attribute id
          #   The unique ID of the local shell call.
          #
          #   @return [String]
          required :id, String

          # @!attribute action
          #   Execute a shell command on the server.
          #
          #   @return [OpenAI::Models::Beta::BetaResponseItem::LocalShellCall::Action]
          required :action, -> { OpenAI::Beta::BetaResponseItem::LocalShellCall::Action }

          # @!attribute call_id
          #   The unique ID of the local shell tool call generated by the model.
          #
          #   @return [String]
          required :call_id, String

          # @!attribute status
          #   The status of the local shell call.
          #
          #   @return [Symbol, OpenAI::Models::Beta::BetaResponseItem::LocalShellCall::Status]
          required :status, enum: -> { OpenAI::Beta::BetaResponseItem::LocalShellCall::Status }

          # @!attribute type
          #   The type of the local shell call. Always `local_shell_call`.
          #
          #   @return [Symbol, :local_shell_call]
          required :type, const: :local_shell_call

          # @!attribute agent
          #   The agent that produced this item.
          #
          #   @return [OpenAI::Models::Beta::BetaResponseItem::LocalShellCall::Agent, nil]
          optional :agent, -> { OpenAI::Beta::BetaResponseItem::LocalShellCall::Agent }, nil?: true

          # @!method initialize(id:, action:, call_id:, status:, agent: nil, type: :local_shell_call)
          #   Some parameter documentations has been truncated, see
          #   {OpenAI::Models::Beta::BetaResponseItem::LocalShellCall} for more details.
          #
          #   A tool call to run a command on the local shell.
          #
          #   @param id [String] The unique ID of the local shell call.
          #
          #   @param action [OpenAI::Models::Beta::BetaResponseItem::LocalShellCall::Action] Execute a shell command on the server.
          #
          #   @param call_id [String] The unique ID of the local shell tool call generated by the model.
          #
          #   @param status [Symbol, OpenAI::Models::Beta::BetaResponseItem::LocalShellCall::Status] The status of the local shell call.
          #
          #   @param agent [OpenAI::Models::Beta::BetaResponseItem::LocalShellCall::Agent, nil] The agent that produced this item.
          #
          #   @param type [Symbol, :local_shell_call] The type of the local shell call. Always `local_shell_call`.

          # @see OpenAI::Models::Beta::BetaResponseItem::LocalShellCall#action
          class Action < OpenAI::Internal::Type::BaseModel
            # @!attribute command
            #   The command to run.
            #
            #   @return [Array<String>]
            required :command, OpenAI::Internal::Type::ArrayOf[String]

            # @!attribute env
            #   Environment variables to set for the command.
            #
            #   @return [Hash{Symbol=>String}]
            required :env, OpenAI::Internal::Type::HashOf[String]

            # @!attribute type
            #   The type of the local shell action. Always `exec`.
            #
            #   @return [Symbol, :exec]
            required :type, const: :exec

            # @!attribute timeout_ms
            #   Optional timeout in milliseconds for the command.
            #
            #   @return [Integer, nil]
            optional :timeout_ms, Integer, nil?: true

            # @!attribute user
            #   Optional user to run the command as.
            #
            #   @return [String, nil]
            optional :user, String, nil?: true

            # @!attribute working_directory
            #   Optional working directory to run the command in.
            #
            #   @return [String, nil]
            optional :working_directory, String, nil?: true

            # @!method initialize(command:, env:, timeout_ms: nil, user: nil, working_directory: nil, type: :exec)
            #   Execute a shell command on the server.
            #
            #   @param command [Array<String>] The command to run.
            #
            #   @param env [Hash{Symbol=>String}] Environment variables to set for the command.
            #
            #   @param timeout_ms [Integer, nil] Optional timeout in milliseconds for the command.
            #
            #   @param user [String, nil] Optional user to run the command as.
            #
            #   @param working_directory [String, nil] Optional working directory to run the command in.
            #
            #   @param type [Symbol, :exec] The type of the local shell action. Always `exec`.
          end

          # The status of the local shell call.
          #
          # @see OpenAI::Models::Beta::BetaResponseItem::LocalShellCall#status
          module Status
            extend OpenAI::Internal::Type::Enum

            IN_PROGRESS = :in_progress
            COMPLETED = :completed
            INCOMPLETE = :incomplete

            # @!method self.values
            #   @return [Array<Symbol>]
          end

          # @see OpenAI::Models::Beta::BetaResponseItem::LocalShellCall#agent
          class Agent < OpenAI::Internal::Type::BaseModel
            # @!attribute agent_name
            #   The canonical name of the agent that produced this item.
            #
            #   @return [String]
            required :agent_name, String

            # @!method initialize(agent_name:)
            #   The agent that produced this item.
            #
            #   @param agent_name [String] The canonical name of the agent that produced this item.
          end
        end

        class LocalShellCallOutput < OpenAI::Internal::Type::BaseModel
          # @!attribute id
          #   The unique ID of the local shell tool call generated by the model.
          #
          #   @return [String]
          required :id, String

          # @!attribute output
          #   A JSON string of the output of the local shell tool call.
          #
          #   @return [String]
          required :output, String

          # @!attribute type
          #   The type of the local shell tool call output. Always `local_shell_call_output`.
          #
          #   @return [Symbol, :local_shell_call_output]
          required :type, const: :local_shell_call_output

          # @!attribute agent
          #   The agent that produced this item.
          #
          #   @return [OpenAI::Models::Beta::BetaResponseItem::LocalShellCallOutput::Agent, nil]
          optional :agent, -> { OpenAI::Beta::BetaResponseItem::LocalShellCallOutput::Agent }, nil?: true

          # @!attribute status
          #   The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          #
          #   @return [Symbol, OpenAI::Models::Beta::BetaResponseItem::LocalShellCallOutput::Status, nil]
          optional(
            :status,
            enum: -> {
              OpenAI::Beta::BetaResponseItem::LocalShellCallOutput::Status
            },
            nil?: true
          )

          # @!method initialize(id:, output:, agent: nil, status: nil, type: :local_shell_call_output)
          #   Some parameter documentations has been truncated, see
          #   {OpenAI::Models::Beta::BetaResponseItem::LocalShellCallOutput} for more details.
          #
          #   The output of a local shell tool call.
          #
          #   @param id [String] The unique ID of the local shell tool call generated by the model.
          #
          #   @param output [String] A JSON string of the output of the local shell tool call.
          #
          #   @param agent [OpenAI::Models::Beta::BetaResponseItem::LocalShellCallOutput::Agent, nil] The agent that produced this item.
          #
          #   @param status [Symbol, OpenAI::Models::Beta::BetaResponseItem::LocalShellCallOutput::Status, nil] The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          #
          #   @param type [Symbol, :local_shell_call_output] The type of the local shell tool call output. Always `local_shell_call_output`.

          # @see OpenAI::Models::Beta::BetaResponseItem::LocalShellCallOutput#agent
          class Agent < OpenAI::Internal::Type::BaseModel
            # @!attribute agent_name
            #   The canonical name of the agent that produced this item.
            #
            #   @return [String]
            required :agent_name, String

            # @!method initialize(agent_name:)
            #   The agent that produced this item.
            #
            #   @param agent_name [String] The canonical name of the agent that produced this item.
          end

          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          #
          # @see OpenAI::Models::Beta::BetaResponseItem::LocalShellCallOutput#status
          module Status
            extend OpenAI::Internal::Type::Enum

            IN_PROGRESS = :in_progress
            COMPLETED = :completed
            INCOMPLETE = :incomplete

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        class McpListTools < OpenAI::Internal::Type::BaseModel
          # @!attribute id
          #   The unique ID of the list.
          #
          #   @return [String]
          required :id, String

          # @!attribute server_label
          #   The label of the MCP server.
          #
          #   @return [String]
          required :server_label, String

          # @!attribute tools
          #   The tools available on the server.
          #
          #   @return [Array<OpenAI::Models::Beta::BetaResponseItem::McpListTools::Tool>]
          required(
            :tools,
            -> { OpenAI::Internal::Type::ArrayOf[OpenAI::Beta::BetaResponseItem::McpListTools::Tool] }
          )

          # @!attribute type
          #   The type of the item. Always `mcp_list_tools`.
          #
          #   @return [Symbol, :mcp_list_tools]
          required :type, const: :mcp_list_tools

          # @!attribute agent
          #   The agent that produced this item.
          #
          #   @return [OpenAI::Models::Beta::BetaResponseItem::McpListTools::Agent, nil]
          optional :agent, -> { OpenAI::Beta::BetaResponseItem::McpListTools::Agent }, nil?: true

          # @!attribute error
          #   Error message if the server could not list tools.
          #
          #   @return [String, nil]
          optional :error, String, nil?: true

          # @!method initialize(id:, server_label:, tools:, agent: nil, error: nil, type: :mcp_list_tools)
          #   Some parameter documentations has been truncated, see
          #   {OpenAI::Models::Beta::BetaResponseItem::McpListTools} for more details.
          #
          #   A list of tools available on an MCP server.
          #
          #   @param id [String] The unique ID of the list.
          #
          #   @param server_label [String] The label of the MCP server.
          #
          #   @param tools [Array<OpenAI::Models::Beta::BetaResponseItem::McpListTools::Tool>] The tools available on the server.
          #
          #   @param agent [OpenAI::Models::Beta::BetaResponseItem::McpListTools::Agent, nil] The agent that produced this item.
          #
          #   @param error [String, nil] Error message if the server could not list tools.
          #
          #   @param type [Symbol, :mcp_list_tools] The type of the item. Always `mcp_list_tools`.

          class Tool < OpenAI::Internal::Type::BaseModel
            # @!attribute input_schema
            #   The JSON schema describing the tool's input.
            #
            #   @return [Object]
            required :input_schema, OpenAI::Internal::Type::Unknown

            # @!attribute name
            #   The name of the tool.
            #
            #   @return [String]
            required :name, String

            # @!attribute annotations
            #   Additional annotations about the tool.
            #
            #   @return [Object, nil]
            optional :annotations, OpenAI::Internal::Type::Unknown, nil?: true

            # @!attribute description
            #   The description of the tool.
            #
            #   @return [String, nil]
            optional :description, String, nil?: true

            # @!method initialize(input_schema:, name:, annotations: nil, description: nil)
            #   Some parameter documentations has been truncated, see
            #   {OpenAI::Models::Beta::BetaResponseItem::McpListTools::Tool} for more details.
            #
            #   A tool available on an MCP server.
            #
            #   @param input_schema [Object] The JSON schema describing the tool's input.
            #
            #   @param name [String] The name of the tool.
            #
            #   @param annotations [Object, nil] Additional annotations about the tool.
            #
            #   @param description [String, nil] The description of the tool.
          end

          # @see OpenAI::Models::Beta::BetaResponseItem::McpListTools#agent
          class Agent < OpenAI::Internal::Type::BaseModel
            # @!attribute agent_name
            #   The canonical name of the agent that produced this item.
            #
            #   @return [String]
            required :agent_name, String

            # @!method initialize(agent_name:)
            #   The agent that produced this item.
            #
            #   @param agent_name [String] The canonical name of the agent that produced this item.
          end
        end

        class McpApprovalRequest < OpenAI::Internal::Type::BaseModel
          # @!attribute id
          #   The unique ID of the approval request.
          #
          #   @return [String]
          required :id, String

          # @!attribute arguments
          #   A JSON string of arguments for the tool.
          #
          #   @return [String]
          required :arguments, String

          # @!attribute name
          #   The name of the tool to run.
          #
          #   @return [String]
          required :name, String

          # @!attribute server_label
          #   The label of the MCP server making the request.
          #
          #   @return [String]
          required :server_label, String

          # @!attribute type
          #   The type of the item. Always `mcp_approval_request`.
          #
          #   @return [Symbol, :mcp_approval_request]
          required :type, const: :mcp_approval_request

          # @!attribute agent
          #   The agent that produced this item.
          #
          #   @return [OpenAI::Models::Beta::BetaResponseItem::McpApprovalRequest::Agent, nil]
          optional :agent, -> { OpenAI::Beta::BetaResponseItem::McpApprovalRequest::Agent }, nil?: true

          # @!method initialize(id:, arguments:, name:, server_label:, agent: nil, type: :mcp_approval_request)
          #   Some parameter documentations has been truncated, see
          #   {OpenAI::Models::Beta::BetaResponseItem::McpApprovalRequest} for more details.
          #
          #   A request for human approval of a tool invocation.
          #
          #   @param id [String] The unique ID of the approval request.
          #
          #   @param arguments [String] A JSON string of arguments for the tool.
          #
          #   @param name [String] The name of the tool to run.
          #
          #   @param server_label [String] The label of the MCP server making the request.
          #
          #   @param agent [OpenAI::Models::Beta::BetaResponseItem::McpApprovalRequest::Agent, nil] The agent that produced this item.
          #
          #   @param type [Symbol, :mcp_approval_request] The type of the item. Always `mcp_approval_request`.

          # @see OpenAI::Models::Beta::BetaResponseItem::McpApprovalRequest#agent
          class Agent < OpenAI::Internal::Type::BaseModel
            # @!attribute agent_name
            #   The canonical name of the agent that produced this item.
            #
            #   @return [String]
            required :agent_name, String

            # @!method initialize(agent_name:)
            #   The agent that produced this item.
            #
            #   @param agent_name [String] The canonical name of the agent that produced this item.
          end
        end

        class McpApprovalResponse < OpenAI::Internal::Type::BaseModel
          # @!attribute id
          #   The unique ID of the approval response
          #
          #   @return [String]
          required :id, String

          # @!attribute approval_request_id
          #   The ID of the approval request being answered.
          #
          #   @return [String]
          required :approval_request_id, String

          # @!attribute approve
          #   Whether the request was approved.
          #
          #   @return [Boolean]
          required :approve, OpenAI::Internal::Type::Boolean

          # @!attribute type
          #   The type of the item. Always `mcp_approval_response`.
          #
          #   @return [Symbol, :mcp_approval_response]
          required :type, const: :mcp_approval_response

          # @!attribute agent
          #   The agent that produced this item.
          #
          #   @return [OpenAI::Models::Beta::BetaResponseItem::McpApprovalResponse::Agent, nil]
          optional :agent, -> { OpenAI::Beta::BetaResponseItem::McpApprovalResponse::Agent }, nil?: true

          # @!attribute reason
          #   Optional reason for the decision.
          #
          #   @return [String, nil]
          optional :reason, String, nil?: true

          # @!method initialize(id:, approval_request_id:, approve:, agent: nil, reason: nil, type: :mcp_approval_response)
          #   Some parameter documentations has been truncated, see
          #   {OpenAI::Models::Beta::BetaResponseItem::McpApprovalResponse} for more details.
          #
          #   A response to an MCP approval request.
          #
          #   @param id [String] The unique ID of the approval response
          #
          #   @param approval_request_id [String] The ID of the approval request being answered.
          #
          #   @param approve [Boolean] Whether the request was approved.
          #
          #   @param agent [OpenAI::Models::Beta::BetaResponseItem::McpApprovalResponse::Agent, nil] The agent that produced this item.
          #
          #   @param reason [String, nil] Optional reason for the decision.
          #
          #   @param type [Symbol, :mcp_approval_response] The type of the item. Always `mcp_approval_response`.

          # @see OpenAI::Models::Beta::BetaResponseItem::McpApprovalResponse#agent
          class Agent < OpenAI::Internal::Type::BaseModel
            # @!attribute agent_name
            #   The canonical name of the agent that produced this item.
            #
            #   @return [String]
            required :agent_name, String

            # @!method initialize(agent_name:)
            #   The agent that produced this item.
            #
            #   @param agent_name [String] The canonical name of the agent that produced this item.
          end
        end

        class McpCall < OpenAI::Internal::Type::BaseModel
          # @!attribute id
          #   The unique ID of the tool call.
          #
          #   @return [String]
          required :id, String

          # @!attribute arguments
          #   A JSON string of the arguments passed to the tool.
          #
          #   @return [String]
          required :arguments, String

          # @!attribute name
          #   The name of the tool that was run.
          #
          #   @return [String]
          required :name, String

          # @!attribute server_label
          #   The label of the MCP server running the tool.
          #
          #   @return [String]
          required :server_label, String

          # @!attribute type
          #   The type of the item. Always `mcp_call`.
          #
          #   @return [Symbol, :mcp_call]
          required :type, const: :mcp_call

          # @!attribute agent
          #   The agent that produced this item.
          #
          #   @return [OpenAI::Models::Beta::BetaResponseItem::McpCall::Agent, nil]
          optional :agent, -> { OpenAI::Beta::BetaResponseItem::McpCall::Agent }, nil?: true

          # @!attribute approval_request_id
          #   Unique identifier for the MCP tool call approval request. Include this value in
          #   a subsequent `mcp_approval_response` input to approve or reject the
          #   corresponding tool call.
          #
          #   @return [String, nil]
          optional :approval_request_id, String, nil?: true

          # @!attribute error
          #   The error from the tool call, if any.
          #
          #   @return [OpenAI::Models::Beta::BetaMcpToolCallError::McpProtocolError, OpenAI::Models::Beta::BetaMcpToolCallError::McpToolExecutionError, OpenAI::Models::Beta::BetaMcpToolCallError::HTTPError, nil]
          optional :error, union: -> { OpenAI::Beta::BetaMcpToolCallError }, nil?: true

          # @!attribute output
          #   The output from the tool call.
          #
          #   @return [String, nil]
          optional :output, String, nil?: true

          # @!attribute status
          #   The status of the tool call. One of `in_progress`, `completed`, `incomplete`,
          #   `calling`, or `failed`.
          #
          #   @return [Symbol, OpenAI::Models::Beta::BetaResponseItem::McpCall::Status, nil]
          optional :status, enum: -> { OpenAI::Beta::BetaResponseItem::McpCall::Status }

          # @!method initialize(id:, arguments:, name:, server_label:, agent: nil, approval_request_id: nil, error: nil, output: nil, status: nil, type: :mcp_call)
          #   Some parameter documentations has been truncated, see
          #   {OpenAI::Models::Beta::BetaResponseItem::McpCall} for more details.
          #
          #   An invocation of a tool on an MCP server.
          #
          #   @param id [String] The unique ID of the tool call.
          #
          #   @param arguments [String] A JSON string of the arguments passed to the tool.
          #
          #   @param name [String] The name of the tool that was run.
          #
          #   @param server_label [String] The label of the MCP server running the tool.
          #
          #   @param agent [OpenAI::Models::Beta::BetaResponseItem::McpCall::Agent, nil] The agent that produced this item.
          #
          #   @param approval_request_id [String, nil] Unique identifier for the MCP tool call approval request.
          #
          #   @param error [OpenAI::Models::Beta::BetaMcpToolCallError::McpProtocolError, OpenAI::Models::Beta::BetaMcpToolCallError::McpToolExecutionError, OpenAI::Models::Beta::BetaMcpToolCallError::HTTPError, nil] The error from the tool call, if any.
          #
          #   @param output [String, nil] The output from the tool call.
          #
          #   @param status [Symbol, OpenAI::Models::Beta::BetaResponseItem::McpCall::Status] The status of the tool call. One of `in_progress`, `completed`, `incomplete`, `c
          #
          #   @param type [Symbol, :mcp_call] The type of the item. Always `mcp_call`.

          # @see OpenAI::Models::Beta::BetaResponseItem::McpCall#agent
          class Agent < OpenAI::Internal::Type::BaseModel
            # @!attribute agent_name
            #   The canonical name of the agent that produced this item.
            #
            #   @return [String]
            required :agent_name, String

            # @!method initialize(agent_name:)
            #   The agent that produced this item.
            #
            #   @param agent_name [String] The canonical name of the agent that produced this item.
          end

          # The status of the tool call. One of `in_progress`, `completed`, `incomplete`,
          # `calling`, or `failed`.
          #
          # @see OpenAI::Models::Beta::BetaResponseItem::McpCall#status
          module Status
            extend OpenAI::Internal::Type::Enum

            IN_PROGRESS = :in_progress
            COMPLETED = :completed
            INCOMPLETE = :incomplete
            CALLING = :calling
            FAILED = :failed

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        # @!method self.variants
        #   @return [Array(OpenAI::Models::Beta::BetaResponseInputMessageItem, OpenAI::Models::Beta::BetaResponseOutputMessage, OpenAI::Models::Beta::BetaResponseFileSearchToolCall, OpenAI::Models::Beta::BetaResponseComputerToolCall, OpenAI::Models::Beta::BetaResponseComputerToolCallOutputItem, OpenAI::Models::Beta::BetaResponseFunctionWebSearch, OpenAI::Models::Beta::BetaResponseFunctionToolCallItem, OpenAI::Models::Beta::BetaResponseFunctionToolCallOutputItem, OpenAI::Models::Beta::BetaResponseItem::AgentMessage, OpenAI::Models::Beta::BetaResponseItem::MultiAgentCall, OpenAI::Models::Beta::BetaResponseItem::MultiAgentCallOutput, OpenAI::Models::Beta::BetaResponseToolSearchCall, OpenAI::Models::Beta::BetaResponseToolSearchOutputItem, OpenAI::Models::Beta::BetaResponseItem::AdditionalTools, OpenAI::Models::Beta::BetaResponseReasoningItem, OpenAI::Models::Beta::BetaResponseItem::Program, OpenAI::Models::Beta::BetaResponseItem::ProgramOutput, OpenAI::Models::Beta::BetaResponseCompactionItem, OpenAI::Models::Beta::BetaResponseItem::ImageGenerationCall, OpenAI::Models::Beta::BetaResponseCodeInterpreterToolCall, OpenAI::Models::Beta::BetaResponseItem::LocalShellCall, OpenAI::Models::Beta::BetaResponseItem::LocalShellCallOutput, OpenAI::Models::Beta::BetaResponseFunctionShellToolCall, OpenAI::Models::Beta::BetaResponseFunctionShellToolCallOutput, OpenAI::Models::Beta::BetaResponseApplyPatchToolCall, OpenAI::Models::Beta::BetaResponseApplyPatchToolCallOutput, OpenAI::Models::Beta::BetaResponseItem::McpListTools, OpenAI::Models::Beta::BetaResponseItem::McpApprovalRequest, OpenAI::Models::Beta::BetaResponseItem::McpApprovalResponse, OpenAI::Models::Beta::BetaResponseItem::McpCall, OpenAI::Models::Beta::BetaResponseCustomToolCallItem, OpenAI::Models::Beta::BetaResponseCustomToolCallOutputItem)]
      end
    end

    BetaResponseItem = Beta::BetaResponseItem
  end
end
